set(PARTOUT_ZIG_SOURCES
build.zig
src/abi/exports.zig
src/abi/helpers.zig
src/abi/runtime.zig
src/c/exports.zig
src/core/actor.zig
src/core/api.zig
src/core/api_extensions.zig
src/core/api_generated.zig
src/core/api_manual.zig
src/core/concurrency.zig
src/core/exports.zig
src/core/logging.zig
src/core/registry.zig
src/core/util.zig
src/core/uuid.zig
src/net/connection.zig
src/net/daemon.zig
src/net/daemon_helpers.zig
src/net/exports.zig
src/net/io.zig
src/net/looper.zig
src/net/looper_queue.zig
src/net/platform.zig
src/net/platform_dns.zig
src/net/sandbox.zig
src/openvpn/connection.zig
src/openvpn/exports.zig
src/openvpn/internal/auth.zig
src/openvpn/internal/configuration.zig
src/openvpn/internal/constants.zig
src/openvpn/internal/control.zig
src/openvpn/internal/crypto.zig
src/openvpn/internal/data.zig
src/openvpn/internal/errors.zig
src/openvpn/internal/helpers.zig
src/openvpn/internal/logging.zig
src/openvpn/internal/packet.zig
src/openvpn/internal/processing.zig
src/openvpn/internal/push.zig
src/openvpn/internal/serialization.zig
src/openvpn/internal/session.zig
src/openvpn/internal/session_context.zig
src/openvpn/internal/session_negotiator.zig
src/openvpn/internal/settings.zig
src/openvpn/internal/tls.zig
src/openvpn/parser.zig
src/openvpn/serializer.zig
src/partout.zig
src/proto/exports.zig
src/testing.zig
src/testing/mock.zig
src/wireguard/connection.zig
src/wireguard/exports.zig
src/wireguard/internal/adapter.zig
src/wireguard/internal/backend.zig
src/wireguard/internal/resolver.zig
src/wireguard/internal/tunnel_info.zig
src/wireguard/internal/uapi.zig
src/wireguard/parser.zig
src/wireguard/serializer.zig
tests/abi/helpers.zig
tests/abi/importer.zig
tests/abi/runtime.zig
tests/all.zig
tests/c/crypto/aead.zig
tests/c/crypto/cbc.zig
tests/c/crypto/ctr.zig
tests/c/crypto/helpers.zig
tests/c/exports.zig
tests/core/actor.zig
tests/core/api.zig
tests/core/api_extensions.zig
tests/core/concurrency.zig
tests/core/logging.zig
tests/core/registry.zig
tests/core/uncovered.zig
tests/core/util.zig
tests/core/uuid.zig
tests/net/connection.zig
tests/net/daemon.zig
tests/net/io.zig
tests/net/looper.zig
tests/net/looper_queue.zig
tests/net/mux.zig
tests/net/platform.zig
tests/net/platform_dns.zig
tests/openvpn/configuration.zig
tests/openvpn/connection.zig
tests/openvpn/exports.zig
tests/openvpn/internal/auth.zig
tests/openvpn/internal/configuration.zig
tests/openvpn/internal/constants.zig
tests/openvpn/internal/control.zig
tests/openvpn/internal/crypto.zig
tests/openvpn/internal/data.zig
tests/openvpn/internal/errors.zig
tests/openvpn/internal/helpers.zig
tests/openvpn/internal/logging.zig
tests/openvpn/internal/packet.zig
tests/openvpn/internal/processing.zig
tests/openvpn/internal/push.zig
tests/openvpn/internal/serialization.zig
tests/openvpn/internal/session.zig
tests/openvpn/internal/session_context.zig
tests/openvpn/internal/session_negotiator.zig
tests/openvpn/internal/settings.zig
tests/openvpn/internal/tls.zig
tests/openvpn/parser.zig
tests/openvpn/serializer.zig
tests/openvpn/uncovered.zig
tests/wireguard/connection.zig
tests/wireguard/exports.zig
tests/wireguard/parser.zig
tests/wireguard/serializer.zig
tools/openapi_codegen.zig
)
set(PARTOUT_C_SOURCES
src/c/crypto/crypto_darwin.c
src/c/crypto/crypto_linux.c
src/c/crypto/crypto_mbedtls.c
src/c/crypto/crypto_mock.c
src/c/crypto/crypto_openssl.c
src/c/crypto/crypto_windows.c
src/c/crypto/tls_options.c
src/c/portable/common.c
src/c/portable/dns.c
src/c/portable/lib.c
src/c/portable/mux.c
src/c/portable/network.c
src/c/portable/prng.c
src/c/portable/socket.c
src/c/portable/tun_android.c
src/c/portable/tun_darwin.c
src/c/portable/tun_linux.c
src/c/portable/tun_windows.c
src/c/portable/zd.c
src/cmake_stub.c
src/openvpn/c/control.c
src/openvpn/c/dp_framing.c
src/openvpn/c/dp_mode.c
src/openvpn/c/dp_mode_ad.c
src/openvpn/c/dp_mode_hmac.c
src/openvpn/c/mss_fix.c
src/openvpn/c/pkt_proc.c
src/openvpn/c/test/openvpn_crypto_mock.c
src/partout.c
src/wireguard/c/backend.c
src/wireguard/c/key.c
src/wireguard/c/x25519.c
)
