included:
  - Sources
excluded:
  - Sources/OpenVPN/OpenVPNOpenSSL_ObjC
  - Sources/Crypto/OpenSSL_ObjC
analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules:
  - sorted_imports
  - missing_docs
disabled_rules:
  - cyclomatic_complexity
  - file_length
  - force_cast
  - function_body_length
  - generic_type_name
  - identifier_name
  - line_length
  - inclusive_language
  - nesting
  - todo
  - type_body_length
