//
// ABIEnvelope.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct ABIEnvelope: Sendable, Codable, Hashable {

    public var code: PartoutErrorCode?
    public var payload: JSON?

    public init(code: PartoutErrorCode? = nil, payload: JSON? = nil) {
        self.code = code
        self.payload = payload
    }
}

