//
// ABIEnvelope.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct ABIEnvelope: Sendable, Codable, Hashable {

    public var code: Int
    public var payload: JSON

    public init(code: Int, payload: JSON) {
        self.code = code
        self.payload = payload
    }
}

