//
// CryptoBackend.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** A cryptographic backend. */
public enum CryptoBackend: Int, Sendable, Codable, CaseIterable {
    case openssl = 1
    case mbedtls = 2
    case native = 3
    case mock = 4
}
