//
// DaemonFeatureFlag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** A daemon feature flag. Values are bit masks combined in the daemon ABI feature_flags field. */
public enum DaemonFeatureFlag: Int, Sendable, Codable, CaseIterable {
    case experimentalDaemon = 1
}
