//
// ModuleImportContextWireGuard.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct ModuleImportContextWireGuard: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case wireGuard = "WireGuard"
    }
    public var type: ModelType

    public init(type: ModelType) {
        self.type = type
    }
}

