//
// ModuleImportContextOpenVPN.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct ModuleImportContextOpenVPN: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case openVPN = "OpenVPN"
    }
    public var type: ModelType
    public var passphrase: String?

    public init(type: ModelType, passphrase: String? = nil) {
        self.type = type
        self.passphrase = passphrase
    }
}

