//
// OpenVPNErrorCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** An OpenVPN-specific error code. */
public enum OpenVPNErrorCode: String, Sendable, Codable, CaseIterable {
    /// Compression settings mismatch.
    case compressionMismatch = "compressionMismatch"
    /// Connection failure.
    case connectionFailure = "connectionFailure"
    /// No routing configuration.
    case noRouting = "noRouting"
    /// One-time password is required.
    case otpRequired = "otpRequired"
    /// Passphrase is required.
    case passphraseRequired = "passphraseRequired"
    /// Authentication can be retried.
    case recoverableAuthentication = "recoverableAuthentication"
    /// Server requested shutdown.
    case serverShutdown = "serverShutdown"
    /// TLS failure.
    case tlsFailure = "tlsFailure"
    /// Algorithm is unsupported.
    case unsupportedAlgorithm = "unsupportedAlgorithm"
    /// Compression setting is unsupported.
    case unsupportedCompression = "unsupportedCompression"
    /// Option is unsupported.
    case unsupportedOption = "unsupportedOption"
}
