//
// ParseErrorInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct ParseErrorInfo: Sendable, Codable, Hashable {

    public var recognizedType: ModuleType?
    public var subCode: String?
    public var name: String?
    public var line: String?
    public var arguments: [String]

    public init(recognizedType: ModuleType? = nil, subCode: String? = nil, name: String? = nil, line: String? = nil, arguments: [String]) {
        self.recognizedType = recognizedType
        self.subCode = subCode
        self.name = name
        self.line = line
        self.arguments = arguments
    }
}

