//
// ParseErrorInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct ParseErrorInfo: Sendable, Codable, Hashable {

    public var errorCode: PartoutErrorCode?
    public var name: String?
    public var line: String?
    public var arguments: [String]

    public init(errorCode: PartoutErrorCode? = nil, name: String? = nil, line: String? = nil, arguments: [String]) {
        self.errorCode = errorCode
        self.name = name
        self.line = line
        self.arguments = arguments
    }
}

