//
// PartoutErrorCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public enum PartoutErrorCode: String, Sendable, Codable, CaseIterable {
    /** OpenVPN error; payload contains an OpenVPNErrorCode in subCode. */
    case openVPN = "openVPN"
    /** WireGuard error; payload contains a WireGuardErrorCode in subCode. */
    case wireGuard = "wireGuard"
    /** Authentication failure. */
    case authentication = "authentication"
    /** Crypto error. */
    case crypto = "crypto"
    /** Decoding error. */
    case decoding = "decoding"
    /** DNS resolution failure. */
    case dnsFailure = "dnsFailure"
    /** Encoding error. */
    case encoding = "encoding"
    /** File descriptor is not available. */
    case fdUnavailable = "fdUnavailable"
    /** Some modules are incompatible (`userInfo` is an array of incompatible ``Module``). */
    case incompatibleModules = "incompatibleModules"
    /** A module is incomplete (`userInfo` is the incomplete ``ModuleBuilder`` ID). */
    case incompleteModule = "incompleteModule"
    /** Invalid field. */
    case invalidField = "invalidField"
    /** Invalid value. */
    case invalidValue = "invalidValue"
    /** I/O failure. */
    case ioFailure = "ioFailure"
    /** Unable to add keychain item. */
    case keychainAddItem = "keychainAddItem"
    /** Keychain item not found. */
    case keychainItemNotFound = "keychainItemNotFound"
    /** Link device is not active. */
    case linkNotActive = "linkNotActive"
    /** Network changed. */
    case networkChanged = "networkChanged"
    /** The profile has no active modules. */
    case noActiveModules = "noActiveModules"
    /** Operation cancelled or unauthorized. */
    case operationCancelled = "operationCancelled"
    /** Memory allocation failed. */
    case outOfMemory = "outOfMemory"
    /** Parsing error. */
    case parsing = "parsing"
    /** A required object was released prematurely. */
    case releasedObject = "releasedObject"
    /** Missing a required implementation. */
    case requiredImplementation = "requiredImplementation"
    /** Native sockets could not be configured. */
    case socketConfiguration = "socketConfiguration"
    /** Operation timed out. */
    case timeout = "timeout"
    /** TUN device is not available for I/O. */
    case tunNotAvailable = "tunNotAvailable"
    /** Generic failure. */
    case unhandled = "unhandled"
    /** Module content is unknown for the importer. */
    case unknownImportedModule = "unknownImportedModule"
    /** Module handler is unknown. */
    case unknownModuleHandler = "unknownModuleHandler"
}
