//
// PartoutErrorPair.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** An error code with an optional protocol-specific subcode. Runtime error strings encode this as code.subCode, or code when subCode is absent. */
public struct PartoutErrorPair: Sendable, Codable, Hashable {

    public var code: PartoutErrorCode
    public var subCode: String?

    public init(code: PartoutErrorCode, subCode: String? = nil) {
        self.code = code
        self.subCode = subCode
    }
}

