//
// TunnelRemoteInfoWrapper.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct TunnelRemoteInfoWrapper: Sendable, Codable, Hashable {

    /** The original profile whose active modules supply platform settings. */
    public var profile: TaggedProfile
    public var originalModuleId: UniqueID
    public var address: Address?
    /** Connection-derived modules to inject immediately after the originating module. Omitted when the profile alone supplies settings. */
    public var modules: [TaggedModule]?

    public init(profile: TaggedProfile, originalModuleId: UniqueID, address: Address? = nil, modules: [TaggedModule]? = nil) {
        self.profile = profile
        self.originalModuleId = originalModuleId
        self.address = address
        self.modules = modules
    }
}

