//
// WireGuardModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** A connection module providing a WireGuard connection. */
public struct WireGuardModule: Sendable, Codable, Hashable {

    public var id: UniqueID
    public var configuration: WireGuardConfiguration?
    public var prefersIPv6: Bool?

    public init(id: UniqueID, configuration: WireGuardConfiguration? = nil, prefersIPv6: Bool? = nil) {
        self.id = id
        self.configuration = configuration
        self.prefersIPv6 = prefersIPv6
    }
}

