/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.models

import io.partout.models.PartoutErrorCode

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param code 
 * @param userInfo 
 */
@Serializable

data class ABIErrorPayload (

    @Contextual @SerialName(value = "code")
    val code: PartoutErrorCode,

    @Contextual @SerialName(value = "userInfo")
    val userInfo: kotlinx.serialization.json.JsonElement? = null

) {


}

