/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.partout.models

import io.partout.models.ModuleType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A type-erased ``Module`` for encoding external implementations.
 *
 * @param innerType 
 * @param json 
 */
@Serializable

data class CustomModule (

    @Contextual @SerialName(value = "innerType")
    val innerType: ModuleType,

    @Contextual @SerialName(value = "json")
    val json: kotlinx.serialization.json.JsonElement

) {


}

