/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.partout.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


/**
 * A daemon feature flag. Values are bit masks combined in the daemon ABI feature_flags field.
 *
 * Values: experimentalDaemon
 */
@Serializable(with = DaemonFeatureFlagSerializer::class)
enum class DaemonFeatureFlag(val value: kotlin.Int) {

    experimentalDaemon(1);

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value.toString()

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is DaemonFeatureFlag) "$data" else null

        /**
         * Returns a valid [DaemonFeatureFlag] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): DaemonFeatureFlag? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object DaemonFeatureFlagSerializer : KSerializer<DaemonFeatureFlag> {
    override val descriptor = kotlin.Int.serializer().descriptor

    override fun deserialize(decoder: Decoder): DaemonFeatureFlag {
        val value = decoder.decodeSerializableValue(kotlin.Int.serializer())
        return DaemonFeatureFlag.entries.firstOrNull { it.value == value }
            ?: throw IllegalArgumentException("Unknown enum value: $value")
    }

    override fun serialize(encoder: Encoder, value: DaemonFeatureFlag) {
        encoder.encodeSerializableValue(kotlin.Int.serializer(), value.value)
    }
}


