/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A pair of received/sent bytes count.
 *
 * @param received Received bytes count.
 * @param sent Sent bytes count.
 */
@Serializable

data class DataCount (

    /* Received bytes count. */
    @SerialName(value = "received")
    val received: kotlin.Long,

    /* Sent bytes count. */
    @SerialName(value = "sent")
    val sent: kotlin.Long

) {


}

