/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * HTTP proxy settings.
 *
 * @param id 
 * @param bypassDomains 
 * @param proxy Represents an endpoint.
 * @param secureProxy Represents an endpoint.
 * @param pacURL 
 */
@Serializable

data class HTTPProxyModule (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "bypassDomains")
    val bypassDomains: kotlin.collections.List<kotlin.String>,

    /* Represents an endpoint. */
    @SerialName(value = "proxy")
    val proxy: kotlin.String? = null,

    /* Represents an endpoint. */
    @SerialName(value = "secureProxy")
    val secureProxy: kotlin.String? = null,

    @SerialName(value = "pacURL")
    val pacURL: kotlin.String? = null

) {


}

