/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.models

import io.partout.models.IPSettings

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * IP and routes.
 *
 * @param id 
 * @param ipv4 
 * @param ipv6 
 * @param mtu 
 */
@Serializable

data class IPModule (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "ipv4")
    val ipv4: IPSettings? = null,

    @SerialName(value = "ipv6")
    val ipv6: IPSettings? = null,

    @SerialName(value = "mtu")
    val mtu: kotlin.Int? = null

) {


}

