/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.models

import io.partout.models.Route

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * IP settings and routes.
 *
 * @param subnets The subnets.
 * @param includedRoutes The included routes.
 * @param excludedRoutes The excluded routes.
 */
@Serializable

data class IPSettings (

    /* The subnets. */
    @SerialName(value = "subnets")
    val subnets: kotlin.collections.List<kotlin.String>,

    /* The included routes. */
    @SerialName(value = "includedRoutes")
    val includedRoutes: kotlin.collections.List<Route>,

    /* The excluded routes. */
    @SerialName(value = "excludedRoutes")
    val excludedRoutes: kotlin.collections.List<Route>

) {


}

