/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.partout.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * Raw type univocally associated to each ``Module`` implementation.
 *
 * Values: Custom,DNS,HTTPProxy,IP,OnDemand,OpenVPN,Provider,WireGuard,Undefined
 */
@Serializable
enum class ModuleType(val value: kotlin.String) {

    @SerialName(value = "Custom")
    Custom("Custom"),

    @SerialName(value = "DNS")
    DNS("DNS"),

    @SerialName(value = "HTTPProxy")
    HTTPProxy("HTTPProxy"),

    @SerialName(value = "IP")
    IP("IP"),

    @SerialName(value = "OnDemand")
    OnDemand("OnDemand"),

    @SerialName(value = "OpenVPN")
    OpenVPN("OpenVPN"),

    @SerialName(value = "Provider")
    Provider("Provider"),

    @SerialName(value = "WireGuard")
    WireGuard("WireGuard"),

    @SerialName(value = "Undefined")
    Undefined("Undefined");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ModuleType) "$data" else null

        /**
         * Returns a valid [ModuleType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ModuleType? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


