/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.partout.models

import io.partout.models.OpenVPNCredentialsOTPMethod

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A set of credentials for authentication.
 *
 * @param username The username.
 * @param password The password.
 * @param otpMethod The OTP method (defaults to none).
 * @param otp The OTP.
 */
@Serializable

data class OpenVPNCredentials (

    /* The username. */
    @SerialName(value = "username")
    val username: kotlin.String,

    /* The password. */
    @SerialName(value = "password")
    val password: kotlin.String,

    /* The OTP method (defaults to none). */
    @Contextual @SerialName(value = "otpMethod")
    val otpMethod: OpenVPNCredentialsOTPMethod,

    /* The OTP. */
    @SerialName(value = "otp")
    val otp: kotlin.String? = null

) {


}

