/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.partout.models

import io.partout.models.OpenVPNStaticKey
import io.partout.models.OpenVPNTLSWrapStrategy

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Holds parameters for TLS wrapping.
 *
 * @param strategy The wrapping strategy.
 * @param key The static encryption key.
 * @param wrappedKey The wrapped client key appended to initial tls-crypt-v2 packets.
 */
@Serializable

data class OpenVPNTLSWrap (

    /* The wrapping strategy. */
    @Contextual @SerialName(value = "strategy")
    val strategy: OpenVPNTLSWrapStrategy,

    /* The static encryption key. */
    @SerialName(value = "key")
    val key: OpenVPNStaticKey,

    /* The wrapped client key appended to initial tls-crypt-v2 packets. */
    @SerialName(value = "wrappedKey")
    val wrappedKey: kotlin.String? = null

) {


}

