/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.models

import io.partout.models.OpenVPNStaticKeyDirection

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Represents an OpenVPN static key file (as generated with --genkey)
 *
 * @param `data` Wrapper of a byte array with safe encoding capabilities.
 * @param dir 
 */
@Serializable

data class OpenVPNStaticKey (

    /* Wrapper of a byte array with safe encoding capabilities. */
    @SerialName(value = "data")
    val `data`: kotlin.String,

    @Contextual @SerialName(value = "dir")
    val dir: OpenVPNStaticKeyDirection? = null

) {


}

