/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.models

import io.partout.models.OpenVPNCredentialsOTPMethod

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A set of credentials for authentication.
 *
 * @param otpMethod The OTP method (defaults to ``OTPMethod-swift.enum/none``).
 * @param password The password.
 * @param username The username.
 * @param otp The OTP.
 */
@Serializable

data class OpenVPNCredentials (

    /* The OTP method (defaults to ``OTPMethod-swift.enum/none``). */
    @Contextual @SerialName(value = "otpMethod")
    val otpMethod: OpenVPNCredentialsOTPMethod,

    /* The password. */
    @SerialName(value = "password")
    val password: kotlin.String,

    /* The username. */
    @SerialName(value = "username")
    val username: kotlin.String,

    /* The OTP. */
    @SerialName(value = "otp")
    val otp: kotlin.String? = null

) {


}

