/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.partout.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * An OpenVPN-specific error code.
 *
 * Values: compressionMismatch,connectionFailure,noRouting,otpRequired,passphraseRequired,recoverableAuthentication,serverShutdown,tlsFailure,unableToDecrypt,unsupportedAlgorithm,unsupportedCompression,unsupportedOption
 */
@Serializable
enum class OpenVPNErrorCode(val value: kotlin.String) {

    /**
     * Compression settings mismatch.
     */
    @SerialName(value = "compressionMismatch")
    compressionMismatch("compressionMismatch"),

    /**
     * Connection failure.
     */
    @SerialName(value = "connectionFailure")
    connectionFailure("connectionFailure"),

    /**
     * No routing configuration.
     */
    @SerialName(value = "noRouting")
    noRouting("noRouting"),

    /**
     * One-time password is required.
     */
    @SerialName(value = "otpRequired")
    otpRequired("otpRequired"),

    /**
     * Passphrase is required.
     */
    @SerialName(value = "passphraseRequired")
    passphraseRequired("passphraseRequired"),

    /**
     * Authentication can be retried.
     */
    @SerialName(value = "recoverableAuthentication")
    recoverableAuthentication("recoverableAuthentication"),

    /**
     * Server requested shutdown.
     */
    @SerialName(value = "serverShutdown")
    serverShutdown("serverShutdown"),

    /**
     * TLS failure.
     */
    @SerialName(value = "tlsFailure")
    tlsFailure("tlsFailure"),

    /**
     * Unable to decrypt configuration.
     */
    @SerialName(value = "unableToDecrypt")
    unableToDecrypt("unableToDecrypt"),

    /**
     * Algorithm is unsupported.
     */
    @SerialName(value = "unsupportedAlgorithm")
    unsupportedAlgorithm("unsupportedAlgorithm"),

    /**
     * Compression setting is unsupported.
     */
    @SerialName(value = "unsupportedCompression")
    unsupportedCompression("unsupportedCompression"),

    /**
     * Option is unsupported.
     */
    @SerialName(value = "unsupportedOption")
    unsupportedOption("unsupportedOption");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is OpenVPNErrorCode) "$data" else null

        /**
         * Returns a valid [OpenVPNErrorCode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): OpenVPNErrorCode? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


