/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.models

import io.partout.models.OpenVPNConfiguration
import io.partout.models.OpenVPNCredentials

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * A connection module providing an OpenVPN connection.
 *
 * @param id 
 * @param configuration 
 * @param credentials 
 * @param requiresInteractiveCredentials 
 */
@Serializable

data class OpenVPNModule (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "configuration")
    val configuration: OpenVPNConfiguration? = null,

    @SerialName(value = "credentials")
    val credentials: OpenVPNCredentials? = null,

    @SerialName(value = "requiresInteractiveCredentials")
    val requiresInteractiveCredentials: kotlin.Boolean? = null

) {


}

