/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.partout.models

import io.partout.models.PartoutErrorCode

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param arguments
 * @param subCode
 * @param name
 * @param line
 */
@Serializable

data class ParseErrorInfo (

    @SerialName(value = "arguments")
    val arguments: kotlin.collections.List<kotlin.String>,

    @Contextual @SerialName(value = "subCode")
    val subCode: PartoutErrorCode? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "line")
    val line: kotlin.String? = null

) {


}
