/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.partout.models

import io.partout.models.PartoutErrorCode

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * An error code with an optional protocol-specific subcode. Runtime error strings encode this as code.subCode, or code when subCode is absent.
 *
 * @param code 
 * @param subCode 
 */
@Serializable

data class PartoutErrorPair (

    @Contextual @SerialName(value = "code")
    val code: PartoutErrorCode,

    @SerialName(value = "subCode")
    val subCode: kotlin.String? = null

) {


}

