/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.partout.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: authentication,cached,crypto,decoding,dnsFailure,encoding,exhaustedEndpoints,fdUnavailable,incompatibleModules,incompleteModule,invalidField,invalidValue,ioFailure,keychainAddItem,keychainItemNotFound,linkNotActive,networkChanged,networkUnreachable,noActiveModules,nonFinalModules,notFound,openVPNCompressionMismatch,openVPNConnectionFailure,openVPNNoRouting,openVPNOTPRequired,openVPNPassphraseRequired,openVPNRecoverableAuthentication,openVPNServerShutdown,openVPNTLSFailure,openVPNUnsupportedAlgorithm,openVPNUnsupportedCompression,openVPNUnsupportedOption,operationCancelled,outOfMemory,parsing,passphraseRequired,releasedObject,requiredImplementation,scriptException,socketConfiguration,timeout,tunNotActive,tunNotAvailable,unexpectedModuleType,unhandled,unknownImportedModule,unknownModuleHandler,wireGuardEmptyPeers
 */
@Serializable
enum class PartoutErrorCode(val value: kotlin.String) {

    @SerialName(value = "authentication")
    authentication("authentication"),

    @SerialName(value = "cached")
    cached("cached"),

    @SerialName(value = "crypto")
    crypto("crypto"),

    @SerialName(value = "decoding")
    decoding("decoding"),

    @SerialName(value = "dnsFailure")
    dnsFailure("dnsFailure"),

    @SerialName(value = "encoding")
    encoding("encoding"),

    @SerialName(value = "exhaustedEndpoints")
    exhaustedEndpoints("exhaustedEndpoints"),

    @SerialName(value = "fdUnavailable")
    fdUnavailable("fdUnavailable"),

    @SerialName(value = "incompatibleModules")
    incompatibleModules("incompatibleModules"),

    @SerialName(value = "incompleteModule")
    incompleteModule("incompleteModule"),

    @SerialName(value = "invalidField")
    invalidField("invalidField"),

    @SerialName(value = "invalidValue")
    invalidValue("invalidValue"),

    @SerialName(value = "ioFailure")
    ioFailure("ioFailure"),

    @SerialName(value = "keychainAddItem")
    keychainAddItem("keychainAddItem"),

    @SerialName(value = "keychainItemNotFound")
    keychainItemNotFound("keychainItemNotFound"),

    @SerialName(value = "linkNotActive")
    linkNotActive("linkNotActive"),

    @SerialName(value = "networkChanged")
    networkChanged("networkChanged"),

    @SerialName(value = "networkUnreachable")
    networkUnreachable("networkUnreachable"),

    @SerialName(value = "noActiveModules")
    noActiveModules("noActiveModules"),

    @SerialName(value = "nonFinalModules")
    nonFinalModules("nonFinalModules"),

    @SerialName(value = "notFound")
    notFound("notFound"),

    @SerialName(value = "OpenVPN.compressionMismatch")
    openVPNCompressionMismatch("OpenVPN.compressionMismatch"),

    @SerialName(value = "OpenVPN.connectionFailure")
    openVPNConnectionFailure("OpenVPN.connectionFailure"),

    @SerialName(value = "OpenVPN.noRouting")
    openVPNNoRouting("OpenVPN.noRouting"),

    @SerialName(value = "OpenVPN.otpRequired")
    openVPNOTPRequired("OpenVPN.otpRequired"),

    @SerialName(value = "OpenVPN.passphraseRequired")
    openVPNPassphraseRequired("OpenVPN.passphraseRequired"),

    @SerialName(value = "OpenVPN.recoverableAuthentication")
    openVPNRecoverableAuthentication("OpenVPN.recoverableAuthentication"),

    @SerialName(value = "OpenVPN.serverShutdown")
    openVPNServerShutdown("OpenVPN.serverShutdown"),

    @SerialName(value = "OpenVPN.tlsFailure")
    openVPNTLSFailure("OpenVPN.tlsFailure"),

    @SerialName(value = "OpenVPN.unsupportedAlgorithm")
    openVPNUnsupportedAlgorithm("OpenVPN.unsupportedAlgorithm"),

    @SerialName(value = "OpenVPN.unsupportedCompression")
    openVPNUnsupportedCompression("OpenVPN.unsupportedCompression"),

    @SerialName(value = "OpenVPN.unsupportedOption")
    openVPNUnsupportedOption("OpenVPN.unsupportedOption"),

    @SerialName(value = "operationCancelled")
    operationCancelled("operationCancelled"),

    @SerialName(value = "outOfMemory")
    outOfMemory("outOfMemory"),

    @SerialName(value = "parsing")
    parsing("parsing"),

    @SerialName(value = "passphraseRequired")
    passphraseRequired("passphraseRequired"),

    @SerialName(value = "releasedObject")
    releasedObject("releasedObject"),

    @SerialName(value = "requiredImplementation")
    requiredImplementation("requiredImplementation"),

    @SerialName(value = "scriptException")
    scriptException("scriptException"),

    @SerialName(value = "socketConfiguration")
    socketConfiguration("socketConfiguration"),

    @SerialName(value = "timeout")
    timeout("timeout"),

    @SerialName(value = "tunNotActive")
    tunNotActive("tunNotActive"),

    @SerialName(value = "tunNotAvailable")
    tunNotAvailable("tunNotAvailable"),

    @SerialName(value = "unexpectedModuleType")
    unexpectedModuleType("unexpectedModuleType"),

    @SerialName(value = "unhandled")
    unhandled("unhandled"),

    @SerialName(value = "unknownImportedModule")
    unknownImportedModule("unknownImportedModule"),

    @SerialName(value = "unknownModuleHandler")
    unknownModuleHandler("unknownModuleHandler"),

    @SerialName(value = "WireGuard.emptyPeers")
    wireGuardEmptyPeers("WireGuard.emptyPeers");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PartoutErrorCode) "$data" else null

        /**
         * Returns a valid [PartoutErrorCode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PartoutErrorCode? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


