/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: cached,notFound,operationCancelled,releasedObject,scriptException,timeout,unhandled,incompatibleModules,incompleteModule,noActiveModules,nonFinalModules,requiredImplementation,unexpectedModuleType,unknownImportedModule,unknownModuleHandler,authentication,crypto,dnsFailure,exhaustedEndpoints,fdUnavailable,ioFailure,linkNotActive,networkChanged,networkUnreachable,socketConfiguration,tunNotActive,tunNotAvailable,decoding,encoding,invalidField,invalidValue,parsing,keychainAddItem,keychainItemNotFound,openVPNCompressionMismatch,openVPNConnectionFailure,openVPNNoRouting,openVPNOTPRequired,openVPNPassphraseRequired,openVPNRecoverableAuthentication,openVPNServerShutdown,openVPNTLSFailure,openVPNUnsupportedAlgorithm,openVPNUnsupportedCompression,openVPNUnsupportedOption,wireGuardEmptyPeers
 */
@Serializable
enum class PartoutErrorCode(val value: kotlin.String) {

    @SerialName(value = "cached")
    cached("cached"),

    @SerialName(value = "notFound")
    notFound("notFound"),

    @SerialName(value = "operationCancelled")
    operationCancelled("operationCancelled"),

    @SerialName(value = "releasedObject")
    releasedObject("releasedObject"),

    @SerialName(value = "scriptException")
    scriptException("scriptException"),

    @SerialName(value = "timeout")
    timeout("timeout"),

    @SerialName(value = "unhandled")
    unhandled("unhandled"),

    @SerialName(value = "incompatibleModules")
    incompatibleModules("incompatibleModules"),

    @SerialName(value = "incompleteModule")
    incompleteModule("incompleteModule"),

    @SerialName(value = "noActiveModules")
    noActiveModules("noActiveModules"),

    @SerialName(value = "nonFinalModules")
    nonFinalModules("nonFinalModules"),

    @SerialName(value = "requiredImplementation")
    requiredImplementation("requiredImplementation"),

    @SerialName(value = "unexpectedModuleType")
    unexpectedModuleType("unexpectedModuleType"),

    @SerialName(value = "unknownImportedModule")
    unknownImportedModule("unknownImportedModule"),

    @SerialName(value = "unknownModuleHandler")
    unknownModuleHandler("unknownModuleHandler"),

    @SerialName(value = "authentication")
    authentication("authentication"),

    @SerialName(value = "crypto")
    crypto("crypto"),

    @SerialName(value = "dnsFailure")
    dnsFailure("dnsFailure"),

    @SerialName(value = "exhaustedEndpoints")
    exhaustedEndpoints("exhaustedEndpoints"),

    @SerialName(value = "fdUnavailable")
    fdUnavailable("fdUnavailable"),

    @SerialName(value = "ioFailure")
    ioFailure("ioFailure"),

    @SerialName(value = "linkNotActive")
    linkNotActive("linkNotActive"),

    @SerialName(value = "networkChanged")
    networkChanged("networkChanged"),

    @SerialName(value = "networkUnreachable")
    networkUnreachable("networkUnreachable"),

    @SerialName(value = "socketConfiguration")
    socketConfiguration("socketConfiguration"),

    @SerialName(value = "tunNotActive")
    tunNotActive("tunNotActive"),

    @SerialName(value = "tunNotAvailable")
    tunNotAvailable("tunNotAvailable"),

    @SerialName(value = "decoding")
    decoding("decoding"),

    @SerialName(value = "encoding")
    encoding("encoding"),

    @SerialName(value = "invalidField")
    invalidField("invalidField"),

    @SerialName(value = "invalidValue")
    invalidValue("invalidValue"),

    @SerialName(value = "parsing")
    parsing("parsing"),

    @SerialName(value = "keychainAddItem")
    keychainAddItem("keychainAddItem"),

    @SerialName(value = "keychainItemNotFound")
    keychainItemNotFound("keychainItemNotFound"),

    @SerialName(value = "OpenVPN.compressionMismatch")
    openVPNCompressionMismatch("OpenVPN.compressionMismatch"),

    @SerialName(value = "OpenVPN.connectionFailure")
    openVPNConnectionFailure("OpenVPN.connectionFailure"),

    @SerialName(value = "OpenVPN.noRouting")
    openVPNNoRouting("OpenVPN.noRouting"),

    @SerialName(value = "OpenVPN.otpRequired")
    openVPNOTPRequired("OpenVPN.otpRequired"),

    @SerialName(value = "OpenVPN.passphraseRequired")
    openVPNPassphraseRequired("OpenVPN.passphraseRequired"),

    @SerialName(value = "OpenVPN.recoverableAuthentication")
    openVPNRecoverableAuthentication("OpenVPN.recoverableAuthentication"),

    @SerialName(value = "OpenVPN.serverShutdown")
    openVPNServerShutdown("OpenVPN.serverShutdown"),

    @SerialName(value = "OpenVPN.tlsFailure")
    openVPNTLSFailure("OpenVPN.tlsFailure"),

    @SerialName(value = "OpenVPN.unsupportedAlgorithm")
    openVPNUnsupportedAlgorithm("OpenVPN.unsupportedAlgorithm"),

    @SerialName(value = "OpenVPN.unsupportedCompression")
    openVPNUnsupportedCompression("OpenVPN.unsupportedCompression"),

    @SerialName(value = "OpenVPN.unsupportedOption")
    openVPNUnsupportedOption("OpenVPN.unsupportedOption"),

    @SerialName(value = "WireGuard.emptyPeers")
    wireGuardEmptyPeers("WireGuard.emptyPeers");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PartoutErrorCode) "$data" else null

        /**
         * Returns a valid [PartoutErrorCode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PartoutErrorCode? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


