/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Advanced flags affecting the behavior of a ``Profile``.
 *
 * @param disconnectsOnSleep Disconnects when the device goes to sleep.
 * @param includesAllNetworks Attempts to route as much traffic as possible through the tunnel.
 */
@Serializable

data class ProfileBehavior (

    /* Disconnects when the device goes to sleep. */
    @SerialName(value = "disconnectsOnSleep")
    val disconnectsOnSleep: kotlin.Boolean,

    /* Attempts to route as much traffic as possible through the tunnel. */
    @SerialName(value = "includesAllNetworks")
    val includesAllNetworks: kotlin.Boolean? = null

) {


}

