/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.partout.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Represents a route in the routing table.
 *
 * @param destination The destination subnet or `nil` if default.
 * @param gateway The address of the gateway (falls back to global gateway).
 */
@Serializable

data class Route (

    /* The destination subnet or `nil` if default. */
    @SerialName(value = "destination")
    val destination: kotlin.String? = null,

    /* The address of the gateway (falls back to global gateway). */
    @SerialName(value = "gateway")
    val gateway: kotlin.String? = null

) {


}

