/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.models

import io.partout.models.DNSModule
import io.partout.models.TaggedModule

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param `value` 
 */
@Serializable

@SerialName(value = "DNS")
data class TaggedModuleDNS (

    @SerialName(value = "value")
    val `value`: DNSModule

) : TaggedModule() {


}

