/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * The status of a ``Tunnel``.
 *
 * Values: inactive,activating,active,deactivating
 */
@Serializable
enum class TunnelStatus(val value: kotlin.String) {

    @SerialName(value = "inactive")
    inactive("inactive"),

    @SerialName(value = "activating")
    activating("activating"),

    @SerialName(value = "active")
    active("active"),

    @SerialName(value = "deactivating")
    deactivating("deactivating");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is TunnelStatus) "$data" else null

        /**
         * Returns a valid [TunnelStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): TunnelStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


