/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.models

import io.partout.models.TaggedModule
import io.partout.models.TaggedProfile
import io.partout.models.TunnelControllerOptions

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param profile 
 * @param options 
 * @param originalModuleId 
 * @param requiresVirtualDevice 
 * @param address A hostname or IP address.
 * @param modules 
 */
@Serializable

data class TunnelRemoteInfoWrapper (

    @SerialName(value = "profile")
    val profile: TaggedProfile,

    @SerialName(value = "options")
    val options: TunnelControllerOptions,

    @SerialName(value = "originalModuleId")
    val originalModuleId: kotlin.String,

    @SerialName(value = "requiresVirtualDevice")
    val requiresVirtualDevice: kotlin.Boolean,

    /* A hostname or IP address. */
    @SerialName(value = "address")
    val address: kotlin.String? = null,

    @SerialName(value = "modules")
    val modules: kotlin.collections.List<TaggedModule>? = null

) {


}

