/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.models

import io.partout.models.TunnelSnapshotEnvironment
import io.partout.models.TunnelStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Returns a tunnel-specific snapshot of a ``Profile``.
 *
 * @param id 
 * @param isEnabled 
 * @param onDemand 
 * @param status 
 * @param environment 
 */
@Serializable

data class TunnelSnapshot (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "isEnabled")
    val isEnabled: kotlin.Boolean,

    @SerialName(value = "onDemand")
    val onDemand: kotlin.Boolean,

    @Contextual @SerialName(value = "status")
    val status: TunnelStatus,

    @SerialName(value = "environment")
    val environment: TunnelSnapshotEnvironment? = null

) {


}

