/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param dnsFallbackServers 
 * @param logsSnapshots 
 * @param minDataCountDelta 
 */
@Serializable

data class TunnelControllerOptions (

    @SerialName(value = "dnsFallbackServers")
    val dnsFallbackServers: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "logsSnapshots")
    val logsSnapshots: kotlin.Boolean,

    @SerialName(value = "minDataCountDelta")
    val minDataCountDelta: kotlin.Long

) {


}

