/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.partout.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * A WireGuard-specific error code.
 *
 * Values: emptyPeers,interfaceHasInvalidAddress,interfaceHasInvalidDNS,interfaceHasInvalidListenPort,interfaceHasInvalidMTU,interfaceHasInvalidPrivateKey,interfaceHasNoPrivateKey,interfaceHasUnrecognizedKey,multipleEntriesForKey,multipleInterfaces,multiplePeersWithSamePublicKey,noInterface,peerHasInvalidAllowedIP,peerHasInvalidEndpoint,peerHasInvalidPersistentKeepAlive,peerHasInvalidPreSharedKey,peerHasInvalidPublicKey,peerHasNoPublicKey,peerHasUnrecognizedKey
 */
@Serializable
enum class WireGuardErrorCode(val value: kotlin.String) {

    @SerialName(value = "emptyPeers")
    emptyPeers("emptyPeers"),

    @SerialName(value = "interfaceHasInvalidAddress")
    interfaceHasInvalidAddress("interfaceHasInvalidAddress"),

    @SerialName(value = "interfaceHasInvalidDNS")
    interfaceHasInvalidDNS("interfaceHasInvalidDNS"),

    @SerialName(value = "interfaceHasInvalidListenPort")
    interfaceHasInvalidListenPort("interfaceHasInvalidListenPort"),

    @SerialName(value = "interfaceHasInvalidMTU")
    interfaceHasInvalidMTU("interfaceHasInvalidMTU"),

    @SerialName(value = "interfaceHasInvalidPrivateKey")
    interfaceHasInvalidPrivateKey("interfaceHasInvalidPrivateKey"),

    @SerialName(value = "interfaceHasNoPrivateKey")
    interfaceHasNoPrivateKey("interfaceHasNoPrivateKey"),

    @SerialName(value = "interfaceHasUnrecognizedKey")
    interfaceHasUnrecognizedKey("interfaceHasUnrecognizedKey"),

    @SerialName(value = "multipleEntriesForKey")
    multipleEntriesForKey("multipleEntriesForKey"),

    @SerialName(value = "multipleInterfaces")
    multipleInterfaces("multipleInterfaces"),

    @SerialName(value = "multiplePeersWithSamePublicKey")
    multiplePeersWithSamePublicKey("multiplePeersWithSamePublicKey"),

    @SerialName(value = "noInterface")
    noInterface("noInterface"),

    @SerialName(value = "peerHasInvalidAllowedIP")
    peerHasInvalidAllowedIP("peerHasInvalidAllowedIP"),

    @SerialName(value = "peerHasInvalidEndpoint")
    peerHasInvalidEndpoint("peerHasInvalidEndpoint"),

    @SerialName(value = "peerHasInvalidPersistentKeepAlive")
    peerHasInvalidPersistentKeepAlive("peerHasInvalidPersistentKeepAlive"),

    @SerialName(value = "peerHasInvalidPreSharedKey")
    peerHasInvalidPreSharedKey("peerHasInvalidPreSharedKey"),

    @SerialName(value = "peerHasInvalidPublicKey")
    peerHasInvalidPublicKey("peerHasInvalidPublicKey"),

    @SerialName(value = "peerHasNoPublicKey")
    peerHasNoPublicKey("peerHasNoPublicKey"),

    @SerialName(value = "peerHasUnrecognizedKey")
    peerHasUnrecognizedKey("peerHasUnrecognizedKey");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is WireGuardErrorCode) "$data" else null

        /**
         * Returns a valid [WireGuardErrorCode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): WireGuardErrorCode? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


