/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.partout.models

import io.partout.models.WireGuardLocalInterface
import io.partout.models.WireGuardRemoteInterface

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * Represents a WireGuard configuration.
 *
 * @param `interface` The local interface.
 * @param peers The peers.
 */
@Serializable

data class WireGuardConfiguration (

    /* The local interface. */
    @SerialName(value = "interface")
    val `interface`: WireGuardLocalInterface,

    /* The peers. */
    @SerialName(value = "peers")
    val peers: kotlin.collections.List<WireGuardRemoteInterface>

) {


}

