/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The parameters of the remote interface.
 *
 * @param allowedIPs The list of allowed subnets.
 * @param publicKey The endpoint public key.
 * @param endpoint The optional endpoint.
 * @param keepAlive The keep-alive interval in seconds.
 * @param preSharedKey The optional endpoint pre-shared key.
 */
@Serializable

data class WireGuardRemoteInterface (

    /* The list of allowed subnets. */
    @SerialName(value = "allowedIPs")
    val allowedIPs: kotlin.collections.List<kotlin.String>,

    /* The endpoint public key. */
    @SerialName(value = "publicKey")
    val publicKey: kotlin.String,

    /* The optional endpoint. */
    @SerialName(value = "endpoint")
    val endpoint: kotlin.String? = null,

    /* The keep-alive interval in seconds. */
    @SerialName(value = "keepAlive")
    val keepAlive: kotlin.Int? = null,

    /* The optional endpoint pre-shared key. */
    @SerialName(value = "preSharedKey")
    val preSharedKey: kotlin.String? = null

) {


}

