/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.partout.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * A WireGuard-specific error code.
 *
 * Values: emptyPeers,interfaceHasInvalidAddress,interfaceHasInvalidDNS,interfaceHasInvalidListenPort,interfaceHasInvalidMTU,interfaceHasInvalidPrivateKey,interfaceHasNoPrivateKey,interfaceHasUnrecognizedKey,multipleEntriesForKey,multipleInterfaces,multiplePeersWithSamePublicKey,noInterface,peerHasInvalidAllowedIP,peerHasInvalidEndpoint,peerHasInvalidPersistentKeepAlive,peerHasInvalidPreSharedKey,peerHasInvalidPublicKey,peerHasNoPublicKey,peerHasUnrecognizedKey
 */
@Serializable
enum class WireGuardErrorCode(val value: kotlin.String) {

    /**
     * Configuration has no peers.
     */
    @SerialName(value = "emptyPeers")
    emptyPeers("emptyPeers"),

    /**
     * Interface address is invalid.
     */
    @SerialName(value = "interfaceHasInvalidAddress")
    interfaceHasInvalidAddress("interfaceHasInvalidAddress"),

    /**
     * Interface DNS entry is invalid.
     */
    @SerialName(value = "interfaceHasInvalidDNS")
    interfaceHasInvalidDNS("interfaceHasInvalidDNS"),

    /**
     * Interface listen port is invalid.
     */
    @SerialName(value = "interfaceHasInvalidListenPort")
    interfaceHasInvalidListenPort("interfaceHasInvalidListenPort"),

    /**
     * Interface MTU is invalid.
     */
    @SerialName(value = "interfaceHasInvalidMTU")
    interfaceHasInvalidMTU("interfaceHasInvalidMTU"),

    /**
     * Interface private key is invalid.
     */
    @SerialName(value = "interfaceHasInvalidPrivateKey")
    interfaceHasInvalidPrivateKey("interfaceHasInvalidPrivateKey"),

    /**
     * Interface has no private key.
     */
    @SerialName(value = "interfaceHasNoPrivateKey")
    interfaceHasNoPrivateKey("interfaceHasNoPrivateKey"),

    /**
     * Interface key is unrecognized.
     */
    @SerialName(value = "interfaceHasUnrecognizedKey")
    interfaceHasUnrecognizedKey("interfaceHasUnrecognizedKey"),

    /**
     * Key occurs more than once.
     */
    @SerialName(value = "multipleEntriesForKey")
    multipleEntriesForKey("multipleEntriesForKey"),

    /**
     * Configuration has multiple interface sections.
     */
    @SerialName(value = "multipleInterfaces")
    multipleInterfaces("multipleInterfaces"),

    /**
     * Configuration has multiple peers with the same public key.
     */
    @SerialName(value = "multiplePeersWithSamePublicKey")
    multiplePeersWithSamePublicKey("multiplePeersWithSamePublicKey"),

    /**
     * Configuration has no interface section.
     */
    @SerialName(value = "noInterface")
    noInterface("noInterface"),

    /**
     * Peer allowed IP is invalid.
     */
    @SerialName(value = "peerHasInvalidAllowedIP")
    peerHasInvalidAllowedIP("peerHasInvalidAllowedIP"),

    /**
     * Peer endpoint is invalid.
     */
    @SerialName(value = "peerHasInvalidEndpoint")
    peerHasInvalidEndpoint("peerHasInvalidEndpoint"),

    /**
     * Peer persistent keepalive is invalid.
     */
    @SerialName(value = "peerHasInvalidPersistentKeepAlive")
    peerHasInvalidPersistentKeepAlive("peerHasInvalidPersistentKeepAlive"),

    /**
     * Peer pre-shared key is invalid.
     */
    @SerialName(value = "peerHasInvalidPreSharedKey")
    peerHasInvalidPreSharedKey("peerHasInvalidPreSharedKey"),

    /**
     * Peer public key is invalid.
     */
    @SerialName(value = "peerHasInvalidPublicKey")
    peerHasInvalidPublicKey("peerHasInvalidPublicKey"),

    /**
     * Peer has no public key.
     */
    @SerialName(value = "peerHasNoPublicKey")
    peerHasNoPublicKey("peerHasNoPublicKey"),

    /**
     * Peer key is unrecognized.
     */
    @SerialName(value = "peerHasUnrecognizedKey")
    peerHasUnrecognizedKey("peerHasUnrecognizedKey");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is WireGuardErrorCode) "$data" else null

        /**
         * Returns a valid [WireGuardErrorCode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): WireGuardErrorCode? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


