/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.models

import io.partout.models.DNSModule

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * The parameters of the local interface.
 *
 * @param privateKey The local private key.
 * @param addresses The local addresses.
 * @param dns The optional DNS settings.
 * @param mtu The optional MTU.
 */
@Serializable

data class WireGuardLocalInterface (

    /* The local private key. */
    @SerialName(value = "privateKey")
    val privateKey: kotlin.String,

    /* The local addresses. */
    @SerialName(value = "addresses")
    val addresses: kotlin.collections.List<kotlin.String>,

    /* The optional DNS settings. */
    @SerialName(value = "dns")
    val dns: DNSModule? = null,

    /* The optional MTU. */
    @SerialName(value = "mtu")
    val mtu: kotlin.Int? = null

) {


}

