set(PARTOUT_SOURCES
./MiniFoundation/Core/EnumeratingRegex.swift
./MiniFoundation/Core/Expectation.swift
./MiniFoundation/Core/PRNG.swift
./MiniFoundation/Core/RandomlyInitialized.swift
./MiniFoundation/Core/UniqueID.swift
./MiniFoundation/Foundation/FileManager+Foundation.swift
./MiniFoundation/Foundation/NSObject+Stream.swift
./MiniFoundation/Foundation/RegularExpression+Foundation.swift
./MiniFoundation/Foundation/String+Foundation.swift
./MiniFoundation/FoundationCompat/CharacterSet.swift
./MiniFoundation/FoundationCompat/Error+Compat.swift
./MiniFoundation/FoundationCompat/FileBuffer.swift
./MiniFoundation/FoundationCompat/FileManager+Compat.swift
./MiniFoundation/FoundationCompat/NSLog.swift
./MiniFoundation/FoundationCompat/RegularExpression+Compat.swift
./MiniFoundation/FoundationCompat/String+Compat.swift
./MiniFoundation/FoundationEssentials/Data+Extensions.swift
./MiniFoundation/FoundationEssentials/Dictionary+Extensions.swift
./MiniFoundation/FoundationEssentials/FileManager+Extensions.swift
./MiniFoundation/FoundationEssentials/JSONCoder+Extensions.swift
./MiniFoundation/FoundationEssentials/String+Extensions.swift
./MiniFoundation/FoundationEssentials/URL+Extensions.swift
./MiniFoundation/JSON/Initialization.swift
./MiniFoundation/JSON/JSON.swift
./MiniFoundation/JSON/Merging.swift
./MiniFoundation/JSON/Querying.swift
./MiniFoundation/MiniFoundation.swift
./MiniFoundation/MiniFoundationError.swift
./MiniFoundation/Streams/AsyncStream+Extensions.swift
./MiniFoundation/Streams/CurrentValueStream.swift
./MiniFoundation/Streams/PassthroughStream.swift
./MiniFoundation/Streams/SubjectStream.swift
./Partout/ABIDaemon.swift
./Partout/ABIHelpers.swift
./Partout/ABI_C.swift
./Partout/PartoutExports.swift
./Partout/Registry+ABI.swift
./PartoutCore/Connection/BetterPathStreamFactory.swift
./PartoutCore/Connection/Connection.swift
./PartoutCore/Connection/ConnectionDaemon.swift
./PartoutCore/Connection/ConnectionFactory.swift
./PartoutCore/Connection/ConnectionModule.swift
./PartoutCore/Connection/ConnectionParameters.swift
./PartoutCore/Connection/DNSResolver.swift
./PartoutCore/Connection/DummyReachabilityObserver.swift
./PartoutCore/Connection/EndpointResolver+Resolvable.swift
./PartoutCore/Connection/EndpointResolver.swift
./PartoutCore/Connection/FdLooper.swift
./PartoutCore/Connection/IOInterface.swift
./PartoutCore/Connection/IPHeader.swift
./PartoutCore/Connection/LinkInterface.swift
./PartoutCore/Connection/LinkObserver.swift
./PartoutCore/Connection/NativeIOInterface.swift
./PartoutCore/Connection/NativeSocketFactory.swift
./PartoutCore/Connection/NativeTunnelController.swift
./PartoutCore/Connection/NetworkInterfaceFactory.swift
./PartoutCore/Connection/NetworkObserver.swift
./PartoutCore/Connection/POSIXDNSStrategy.swift
./PartoutCore/Connection/ReachabilityInfo.swift
./PartoutCore/Connection/ReachabilityObserver.swift
./PartoutCore/Connection/SharedTunnelEnvironment.swift
./PartoutCore/Connection/Side.swift
./PartoutCore/Connection/SimpleConnectionDaemon.swift
./PartoutCore/Connection/SimpleDNSResolver.swift
./PartoutCore/Connection/SocketWrapper.swift
./PartoutCore/Connection/StaticTunnelEnvironment.swift
./PartoutCore/Connection/TunInterface.swift
./PartoutCore/Connection/TunWrapper.swift
./PartoutCore/Connection/TunnelController.swift
./PartoutCore/Connection/TunnelEnvironment.swift
./PartoutCore/Connection/TunnelEnvironmentKeys+Connection.swift
./PartoutCore/Connection/TunnelEnvironmentKeys.swift
./PartoutCore/Connection/TunnelRemoteInfo.swift
./PartoutCore/Data/CZeroingData+Shortcuts.swift
./PartoutCore/Data/CZeroingData.swift
./PartoutCore/Data/Data+Manipulation.swift
./PartoutCore/Data/Data+Network.swift
./PartoutCore/Data/Data+Zeroing.swift
./PartoutCore/Legacy/LegacyModuleDecoder.swift
./PartoutCore/Legacy/LegacyProfileEncoderV2.swift
./PartoutCore/Legacy/ModuleHandler+Extensions.swift
./PartoutCore/Legacy/ModuleHandler.swift
./PartoutCore/Logging/DebugLog.swift
./PartoutCore/Logging/Encoder+Sensitive.swift
./PartoutCore/Logging/Foundation+Sensitive.swift
./PartoutCore/Logging/LocalLogger+FileStrategy.swift
./PartoutCore/Logging/LocalLogger.swift
./PartoutCore/Logging/LoggableModule.swift
./PartoutCore/Logging/LoggerCategory.swift
./PartoutCore/Logging/LoggerDestination.swift
./PartoutCore/Logging/PPLog.swift
./PartoutCore/Logging/PartoutLogger.swift
./PartoutCore/Logging/SensitiveDebugStringConvertible+Extensions.swift
./PartoutCore/Logging/SensitiveDebugStringConvertible.swift
./PartoutCore/Logging/SimpleLogDestination.swift
./PartoutCore/Misc/BidirectionalState.swift
./PartoutCore/Misc/DataUnit.swift
./PartoutCore/Misc/FileDescriptor.swift
./PartoutCore/Misc/Keychain.swift
./PartoutCore/Misc/RingQueue.swift
./PartoutCore/Misc/ScriptingEngine.swift
./PartoutCore/Misc/SemaphoreMutex.swift
./PartoutCore/Misc/Swift+Extensions.swift
./PartoutCore/Misc/Task+Extensions.swift
./PartoutCore/Misc/TimeInterval+Extensions.swift
./PartoutCore/OpenAPI/Codegen/ABIErrorPayload.swift
./PartoutCore/OpenAPI/Codegen/ConnectionStatus.swift
./PartoutCore/OpenAPI/Codegen/CustomModule.swift
./PartoutCore/OpenAPI/Codegen/DNSModule.swift
./PartoutCore/OpenAPI/Codegen/DNSModuleDomainPolicy.swift
./PartoutCore/OpenAPI/Codegen/DNSModuleProtocolTypeCleartext.swift
./PartoutCore/OpenAPI/Codegen/DNSModuleProtocolTypeHttps.swift
./PartoutCore/OpenAPI/Codegen/DNSModuleProtocolTypeTls.swift
./PartoutCore/OpenAPI/Codegen/DNSProtocol.swift
./PartoutCore/OpenAPI/Codegen/DataCount.swift
./PartoutCore/OpenAPI/Codegen/HTTPProxyModule.swift
./PartoutCore/OpenAPI/Codegen/IPModule.swift
./PartoutCore/OpenAPI/Codegen/IPSettings.swift
./PartoutCore/OpenAPI/Codegen/IPSocketType.swift
./PartoutCore/OpenAPI/Codegen/ModuleType.swift
./PartoutCore/OpenAPI/Codegen/OnDemandModule.swift
./PartoutCore/OpenAPI/Codegen/OnDemandModuleOtherNetwork.swift
./PartoutCore/OpenAPI/Codegen/OnDemandModulePolicy.swift
./PartoutCore/OpenAPI/Codegen/OpenVPNCipher.swift
./PartoutCore/OpenAPI/Codegen/OpenVPNCompressionAlgorithm.swift
./PartoutCore/OpenAPI/Codegen/OpenVPNCompressionFraming.swift
./PartoutCore/OpenAPI/Codegen/OpenVPNConfiguration.swift
./PartoutCore/OpenAPI/Codegen/OpenVPNCredentials.swift
./PartoutCore/OpenAPI/Codegen/OpenVPNCredentialsOTPMethod.swift
./PartoutCore/OpenAPI/Codegen/OpenVPNDigest.swift
./PartoutCore/OpenAPI/Codegen/OpenVPNModule.swift
./PartoutCore/OpenAPI/Codegen/OpenVPNObfuscationMethodObfuscate.swift
./PartoutCore/OpenAPI/Codegen/OpenVPNObfuscationMethodReverse.swift
./PartoutCore/OpenAPI/Codegen/OpenVPNObfuscationMethodXormask.swift
./PartoutCore/OpenAPI/Codegen/OpenVPNObfuscationMethodXorptrpos.swift
./PartoutCore/OpenAPI/Codegen/OpenVPNPullMask.swift
./PartoutCore/OpenAPI/Codegen/OpenVPNRoutingPolicy.swift
./PartoutCore/OpenAPI/Codegen/OpenVPNStaticKey.swift
./PartoutCore/OpenAPI/Codegen/OpenVPNStaticKeyDirection.swift
./PartoutCore/OpenAPI/Codegen/OpenVPNTLSWrap.swift
./PartoutCore/OpenAPI/Codegen/OpenVPNTLSWrapStrategy.swift
./PartoutCore/OpenAPI/Codegen/PartoutErrorCode.swift
./PartoutCore/OpenAPI/Codegen/ProfileBehavior.swift
./PartoutCore/OpenAPI/Codegen/Route.swift
./PartoutCore/OpenAPI/Codegen/SocketType.swift
./PartoutCore/OpenAPI/Codegen/TaggedModuleCustom.swift
./PartoutCore/OpenAPI/Codegen/TaggedModuleDNS.swift
./PartoutCore/OpenAPI/Codegen/TaggedModuleHTTPProxy.swift
./PartoutCore/OpenAPI/Codegen/TaggedModuleIP.swift
./PartoutCore/OpenAPI/Codegen/TaggedModuleOnDemand.swift
./PartoutCore/OpenAPI/Codegen/TaggedModuleOpenVPN.swift
./PartoutCore/OpenAPI/Codegen/TaggedModuleWireGuard.swift
./PartoutCore/OpenAPI/Codegen/TaggedProfile.swift
./PartoutCore/OpenAPI/Codegen/TunnelControllerOptions.swift
./PartoutCore/OpenAPI/Codegen/TunnelRemoteInfoWrapper.swift
./PartoutCore/OpenAPI/Codegen/TunnelSnapshot.swift
./PartoutCore/OpenAPI/Codegen/TunnelSnapshotEnvironment.swift
./PartoutCore/OpenAPI/Codegen/TunnelStatus.swift
./PartoutCore/OpenAPI/Codegen/WireGuardConfiguration.swift
./PartoutCore/OpenAPI/Codegen/WireGuardLocalInterface.swift
./PartoutCore/OpenAPI/Codegen/WireGuardModule.swift
./PartoutCore/OpenAPI/Codegen/WireGuardRemoteInterface.swift
./PartoutCore/OpenAPI/Extensions/Aliases.swift
./PartoutCore/OpenAPI/Extensions/Core/Address.swift
./PartoutCore/OpenAPI/Extensions/Core/ConnectionStatus+Extensions.swift
./PartoutCore/OpenAPI/Extensions/Core/DataCount+Extensions.swift
./PartoutCore/OpenAPI/Extensions/Core/Endpoint.swift
./PartoutCore/OpenAPI/Extensions/Core/EndpointProtocol.swift
./PartoutCore/OpenAPI/Extensions/Core/ExtendedEndpoint+Socket.swift
./PartoutCore/OpenAPI/Extensions/Core/ExtendedEndpoint.swift
./PartoutCore/OpenAPI/Extensions/Core/IPSettings+Extensions.swift
./PartoutCore/OpenAPI/Extensions/Core/ModuleType+Extensions.swift
./PartoutCore/OpenAPI/Extensions/Core/ProfileBehavior+Extensions.swift
./PartoutCore/OpenAPI/Extensions/Core/Route+Extensions.swift
./PartoutCore/OpenAPI/Extensions/Core/SecureData.swift
./PartoutCore/OpenAPI/Extensions/Core/SocketType+Extensions.swift
./PartoutCore/OpenAPI/Extensions/Core/Subnet.swift
./PartoutCore/OpenAPI/Extensions/Core/TunnelControllerOptions+Extensions.swift
./PartoutCore/OpenAPI/Extensions/Core/TunnelRemoteInfoWrapper+Extensions.swift
./PartoutCore/OpenAPI/Extensions/Core/TunnelSnapshot+Extensions.swift
./PartoutCore/OpenAPI/Extensions/Core/TunnelStatus+Extensions.swift
./PartoutCore/OpenAPI/Extensions/Modules/CustomModule+Extensions.swift
./PartoutCore/OpenAPI/Extensions/Modules/DNSModule+Extensions.swift
./PartoutCore/OpenAPI/Extensions/Modules/DNSProtocol+Extensions.swift
./PartoutCore/OpenAPI/Extensions/Modules/HTTPProxyModule+Extensions.swift
./PartoutCore/OpenAPI/Extensions/Modules/IPModule+Extensions.swift
./PartoutCore/OpenAPI/Extensions/Modules/OnDemandModule+Extensions.swift
./PartoutCore/OpenAPI/Extensions/OpenVPN/CompressionAlgorithm.swift
./PartoutCore/OpenAPI/Extensions/OpenVPN/CompressionFraming.swift
./PartoutCore/OpenAPI/Extensions/OpenVPN/Credentials.swift
./PartoutCore/OpenAPI/Extensions/OpenVPN/CryptoContainer.swift
./PartoutCore/OpenAPI/Extensions/OpenVPN/ObfuscationMethod.swift
./PartoutCore/OpenAPI/Extensions/OpenVPN/OpenVPN+Configuration.swift
./PartoutCore/OpenAPI/Extensions/OpenVPN/OpenVPN.swift
./PartoutCore/OpenAPI/Extensions/OpenVPN/OpenVPNModule+Extensions.swift
./PartoutCore/OpenAPI/Extensions/OpenVPN/StaticKey.swift
./PartoutCore/OpenAPI/Extensions/OpenVPN/TLSWrap.swift
./PartoutCore/OpenAPI/Extensions/PartoutError+Code.swift
./PartoutCore/OpenAPI/Extensions/TaggedModule+Extensions.swift
./PartoutCore/OpenAPI/Extensions/TaggedModule.swift
./PartoutCore/OpenAPI/Extensions/TaggedProfile+Extensions.swift
./PartoutCore/OpenAPI/Extensions/WireGuard/Key.swift
./PartoutCore/OpenAPI/Extensions/WireGuard/LocalInterface.swift
./PartoutCore/OpenAPI/Extensions/WireGuard/RemoteInterface.swift
./PartoutCore/OpenAPI/Extensions/WireGuard/WireGuard+Configuration.swift
./PartoutCore/OpenAPI/Extensions/WireGuard/WireGuard.swift
./PartoutCore/OpenAPI/Extensions/WireGuard/WireGuardModule+Extensions.swift
./PartoutCore/PRNG/PRNGProtocol+Suite.swift
./PartoutCore/PRNG/PRNGProtocol.swift
./PartoutCore/PRNG/PlatformPRNG.swift
./PartoutCore/PRNG/SimplePRNG.swift
./PartoutCore/Partout+Core.swift
./PartoutCore/PartoutConstants.swift
./PartoutCore/Profile/Builder.swift
./PartoutCore/Profile/Module+Defaults.swift
./PartoutCore/Profile/Module+Hashable.swift
./PartoutCore/Profile/Module.swift
./PartoutCore/Profile/ModuleBuilder.swift
./PartoutCore/Profile/PartoutError.swift
./PartoutCore/Profile/Profile+Diff.swift
./PartoutCore/Profile/Profile.swift
./PartoutCore/Profile/ProfileHeader.swift
./PartoutCore/Profile/ProfileType+Extensions.swift
./PartoutCore/Profile/ProfileType.swift
./PartoutCore/Registry/ModuleBuilderValidator.swift
./PartoutCore/Registry/ModuleImplementation.swift
./PartoutCore/Registry/ModuleImporter.swift
./PartoutCore/Registry/ModuleRegistry.swift
./PartoutCore/Registry/Registry+Support.swift
./PartoutCore/Registry/Registry.swift
./PartoutCore/Registry/Resolver.swift
./PartoutCore/Serialization/CodingRegistry.swift
./PartoutCore/Serialization/CodingUserInfoKey+Modules.swift
./PartoutCore/Serialization/ConfigurationCoder.swift
./PartoutCore/Serialization/ProfileCoder.swift
./PartoutCore/Serialization/ProfileEncoderV3.swift
./PartoutCore/Testing/MockDNSResolver.swift
./PartoutCore/Testing/MockLinkInterface.swift
./PartoutCore/Testing/MockNetworkInterfaceFactory.swift
./PartoutCore/Testing/MockTunnelController.swift
./PartoutCore/Testing/MockTunnelInterface.swift
./PartoutCore/Tunnel/DefaultMessageHandler.swift
./PartoutCore/Tunnel/FakeTunnelStrategy.swift
./PartoutCore/Tunnel/MessageHandler.swift
./PartoutCore/Tunnel/Tunnel.swift
./PartoutCore/Tunnel/TunnelStrategy.swift
./PartoutOS/Apple/AppleJavaScriptEngine.swift
./PartoutOS/Apple/AppleKeychain.swift
./PartoutOS/Apple/AppleRandom.swift
./PartoutOS/Apple/BundleConfiguration.swift
./PartoutOS/Apple/OSLogDestination.swift
./PartoutOS/Apple/PartoutTunnelObservable.swift
./PartoutOS/Apple/UserDefaultsEnvironment.swift
./PartoutOS/AppleNE/App/NETunnelEnvironment.swift
./PartoutOS/AppleNE/App/NETunnelManagerRepository.swift
./PartoutOS/AppleNE/App/NETunnelStrategy.swift
./PartoutOS/AppleNE/AppExtension/NEBetterPathStreamFactory.swift
./PartoutOS/AppleNE/AppExtension/NEObservablePath.swift
./PartoutOS/AppleNE/AppExtension/NEPTPForwarder.swift
./PartoutOS/AppleNE/AppExtension/NESettingsApplying.swift
./PartoutOS/AppleNE/AppExtension/NESettingsModule.swift
./PartoutOS/AppleNE/Connection/NEInterfaceFactory.swift
./PartoutOS/AppleNE/Connection/NETCPSocket.swift
./PartoutOS/AppleNE/Connection/NETunnelController.swift
./PartoutOS/AppleNE/Connection/NETunnelInterface.swift
./PartoutOS/AppleNE/Connection/NEUDPSocket.swift
./PartoutOS/AppleNE/Connection/SafeValueObserver.swift
./PartoutOS/AppleNE/Connection/ValueObserver.swift
./PartoutOS/AppleNE/Extensions/Module+Requirements.swift
./PartoutOS/AppleNE/Extensions/NE+Hacks.swift
./PartoutOS/AppleNE/Extensions/NEIPv4Route+Equatable.swift
./PartoutOS/AppleNE/Extensions/NEIPv4Settings+DebugDescription.swift
./PartoutOS/AppleNE/Extensions/NEIPv6Route+Equatable.swift
./PartoutOS/AppleNE/Extensions/NEIPv6Settings+DebugDescription.swift
./PartoutOS/AppleNE/Extensions/NEOnDemandRule+Equatable.swift
./PartoutOS/AppleNE/Extensions/NWConnectionState+Description.swift
./PartoutOS/AppleNE/Extensions/NWTCPConnectionState+Description.swift
./PartoutOS/AppleNE/Extensions/NWUDPSessionState+Description.swift
./PartoutOS/AppleNE/Extensions/OnDemandModule+Support.swift
./PartoutOS/AppleNE/Modules/DNSModule+NE.swift
./PartoutOS/AppleNE/Modules/HTTPProxyModule+NE.swift
./PartoutOS/AppleNE/Modules/IPModule+NE.swift
./PartoutOS/AppleNE/Modules/OnDemandModule+NE.swift
./PartoutOS/AppleNE/Modules/Profile+NE.swift
./PartoutOS/AppleNE/Serialization/KeychainNEProtocolCoder.swift
./PartoutOS/AppleNE/Serialization/NEProtocolCoder.swift
./PartoutOS/AppleNE/Serialization/ProviderNEProtocolCoder.swift
./PartoutOS/Partout+OS.swift
./PartoutOpenVPN/Internal/Aliases+Cross.swift
./PartoutOpenVPN/Internal/AuthSerializer.swift
./PartoutOpenVPN/Internal/Authenticator.swift
./PartoutOpenVPN/Internal/CControlPacket+Serialization.swift
./PartoutOpenVPN/Internal/CControlPacket.swift
./PartoutOpenVPN/Internal/CDataPath.swift
./PartoutOpenVPN/Internal/CPacketCode.swift
./PartoutOpenVPN/Internal/CPacketProtocol.swift
./PartoutOpenVPN/Internal/CZeroingData+HMAC.swift
./PartoutOpenVPN/Internal/Constants.swift
./PartoutOpenVPN/Internal/ControlChannel+Cross.swift
./PartoutOpenVPN/Internal/ControlChannel.swift
./PartoutOpenVPN/Internal/ControlChannelSerializer.swift
./PartoutOpenVPN/Internal/CryptSerializer.swift
./PartoutOpenVPN/Internal/CryptV2Serializer.swift
./PartoutOpenVPN/Internal/CryptoError.swift
./PartoutOpenVPN/Internal/CryptoFactories.swift
./PartoutOpenVPN/Internal/CryptoKeys+PRF.swift
./PartoutOpenVPN/Internal/CryptoKeys.swift
./PartoutOpenVPN/Internal/DataChannel.swift
./PartoutOpenVPN/Internal/DataPathError.swift
./PartoutOpenVPN/Internal/DataPathProtocol.swift
./PartoutOpenVPN/Internal/DataPathWrapper+Native.swift
./PartoutOpenVPN/Internal/DataPathWrapper.swift
./PartoutOpenVPN/Internal/Error+Recoverable.swift
./PartoutOpenVPN/Internal/ExtendedEndpoint+Random.swift
./PartoutOpenVPN/Internal/Handshake.swift
./PartoutOpenVPN/Internal/NegotiationHistory.swift
./PartoutOpenVPN/Internal/Negotiator.swift
./PartoutOpenVPN/Internal/NetworkSettingsBuilder.swift
./PartoutOpenVPN/Internal/OCCPacket.swift
./PartoutOpenVPN/Internal/OpenVPNActor.swift
./PartoutOpenVPN/Internal/OpenVPNConfiguration+CipherNegotiation.swift
./PartoutOpenVPN/Internal/OpenVPNErrorCode+Cross.swift
./PartoutOpenVPN/Internal/OpenVPNSession+Data.swift
./PartoutOpenVPN/Internal/OpenVPNSession+Loop.swift
./PartoutOpenVPN/Internal/OpenVPNSession+Negotiation.swift
./PartoutOpenVPN/Internal/OpenVPNSession.swift
./PartoutOpenVPN/Internal/OpenVPNSessionError+Mapping.swift
./PartoutOpenVPN/Internal/OpenVPNSessionError.swift
./PartoutOpenVPN/Internal/OpenVPNSessionProtocol.swift
./PartoutOpenVPN/Internal/OpenVPNTCPLink.swift
./PartoutOpenVPN/Internal/OpenVPNUDPLink.swift
./PartoutOpenVPN/Internal/PIAHardReset.swift
./PartoutOpenVPN/Internal/PacketProcessor.swift
./PartoutOpenVPN/Internal/PlainSerializer.swift
./PartoutOpenVPN/Internal/PushReply.swift
./PartoutOpenVPN/Internal/RenegotiationType.swift
./PartoutOpenVPN/Internal/ServerOCC.swift
./PartoutOpenVPN/Internal/SimpleKeyDecrypter.swift
./PartoutOpenVPN/Internal/TLSError.swift
./PartoutOpenVPN/Internal/TLSProtocol.swift
./PartoutOpenVPN/Internal/TLSWrapper+Native.swift
./PartoutOpenVPN/Internal/TLSWrapper.swift
./PartoutOpenVPN/KeyDecrypter.swift
./PartoutOpenVPN/OpenVPN+Extensions.swift
./PartoutOpenVPN/OpenVPN+Serialization.swift
./PartoutOpenVPN/OpenVPNConnectionOptions.swift
./PartoutOpenVPN/OpenVPNModule+Implementation.swift
./PartoutOpenVPN/OpenVPNOption.swift
./PartoutOpenVPN/StandardOpenVPNParser+Builder.swift
./PartoutOpenVPN/StandardOpenVPNParser+Default.swift
./PartoutOpenVPN/StandardOpenVPNParser.swift
./PartoutOpenVPN/StandardOpenVPNParserError.swift
./PartoutOpenVPN/V2/_OpenVPNConnectionV2+Default.swift
./PartoutOpenVPN/V2/_OpenVPNConnectionV2.swift
./PartoutOpenVPN/V3/Internal/ControlChannelV3+Cross.swift
./PartoutOpenVPN/V3/Internal/ControlChannelV3.swift
./PartoutOpenVPN/V3/Internal/LinkProcessor.swift
./PartoutOpenVPN/V3/Internal/NegotiatorV3.swift
./PartoutOpenVPN/V3/Internal/OpenVPNSessionProtocolV3.swift
./PartoutOpenVPN/V3/Internal/OpenVPNSessionV3+Context.swift
./PartoutOpenVPN/V3/Internal/OpenVPNSessionV3+Data.swift
./PartoutOpenVPN/V3/Internal/OpenVPNSessionV3+Loop.swift
./PartoutOpenVPN/V3/Internal/OpenVPNSessionV3+Negotiation.swift
./PartoutOpenVPN/V3/Internal/OpenVPNSessionV3.swift
./PartoutOpenVPN/V3/_OpenVPNConnectionV3+Default.swift
./PartoutOpenVPN/V3/_OpenVPNConnectionV3.swift
./PartoutWireGuard/Internal/Configuration+WgQuickConfig.swift
./PartoutWireGuard/Internal/Endpoint+WireGuardKit.swift
./PartoutWireGuard/Internal/PrivateKey.swift
./PartoutWireGuard/Internal/String+ArrayConversion.swift
./PartoutWireGuard/Internal/WireGuardBackend.swift
./PartoutWireGuard/StandardWireGuardKeyGenerator.swift
./PartoutWireGuard/StandardWireGuardParser+Validate.swift
./PartoutWireGuard/StandardWireGuardParser.swift
./PartoutWireGuard/V2/Internal/Configuration+Resolve.swift
./PartoutWireGuard/V2/Internal/String+Base64Hex.swift
./PartoutWireGuard/V2/Internal/TunnelRemoteInfoGenerator.swift
./PartoutWireGuard/V2/Internal/WireGuardAdapter.swift
./PartoutWireGuard/V2/Internal/WireGuardAdapterError.swift
./PartoutWireGuard/V2/_WireGuardConnectionV2.swift
./PartoutWireGuard/WireGuard+Extensions.swift
./PartoutWireGuard/WireGuardConnectionError.swift
./PartoutWireGuard/WireGuardKeyGenerator.swift
./PartoutWireGuard/WireGuardModule+Implementation.swift
./PartoutWireGuard/WireGuardParseError.swift
)
set(PARTOUT_C_SOURCES
./MiniFoundation_C/rx.cc
./MiniFoundation_C/std.c
./PartoutCore_C/common.c
./PartoutCore_C/file.c
./PartoutCore_C/lib.c
./PartoutCore_C/mux.c
./PartoutCore_C/network.c
./PartoutCore_C/prng.c
./PartoutCore_C/socket.c
./PartoutCore_C/tls_options.c
./PartoutCore_C/tun_android.c
./PartoutCore_C/tun_darwin.c
./PartoutCore_C/tun_linux.c
./PartoutCore_C/tun_windows.c
./PartoutCore_C/zd.c
./PartoutCrypto/Native_C/src/android/crypto.c
./PartoutCrypto/Native_C/src/android/hmac.c
./PartoutCrypto/Native_C/src/darwin/crypto.c
./PartoutCrypto/Native_C/src/darwin/crypto_aead.c
./PartoutCrypto/Native_C/src/darwin/crypto_cbc.c
./PartoutCrypto/Native_C/src/darwin/crypto_ctr.c
./PartoutCrypto/Native_C/src/darwin/hmac.c
./PartoutCrypto/Native_C/src/linux/crypto.c
./PartoutCrypto/Native_C/src/linux/hmac.c
./PartoutCrypto/Native_C/src/mbed/keys.c
./PartoutCrypto/Native_C/src/mbed/tls.c
./PartoutCrypto/Native_C/src/windows/crypto.c
./PartoutCrypto/Native_C/src/windows/crypto_aead.c
./PartoutCrypto/Native_C/src/windows/crypto_cbc.c
./PartoutCrypto/Native_C/src/windows/crypto_ctr.c
./PartoutCrypto/Native_C/src/windows/hmac.c
./PartoutCrypto/OpenSSL_C/crypto.c
./PartoutCrypto/OpenSSL_C/crypto_aead.c
./PartoutCrypto/OpenSSL_C/crypto_cbc.c
./PartoutCrypto/OpenSSL_C/crypto_ctr.c
./PartoutCrypto/OpenSSL_C/hmac.c
./PartoutCrypto/OpenSSL_C/keys.c
./PartoutCrypto/OpenSSL_C/tls.c
./PartoutOpenVPN_C/control.c
./PartoutOpenVPN_C/dp_framing.c
./PartoutOpenVPN_C/dp_mode.c
./PartoutOpenVPN_C/dp_mode_ad.c
./PartoutOpenVPN_C/dp_mode_hmac.c
./PartoutOpenVPN_C/logging.c
./PartoutOpenVPN_C/mss_fix.c
./PartoutOpenVPN_C/pkt_proc.c
./PartoutOpenVPN_C/test/crypto_mock.c
./PartoutWireGuardBackend_C/backend.c
./PartoutWireGuard_C/key.c
./PartoutWireGuard_C/logging.c
./PartoutWireGuard_C/x25519.c
./Partout_C/partout.c
)
