set(PARTOUT_C_SOURCES
./PartoutWireGuard_C/x25519.c
./PartoutWireGuard_C/key.c
./PartoutWireGuard_C/logging.c
./PartoutOpenVPNConnection_C/dp_mode_hmac.c
./PartoutOpenVPNConnection_C/test/crypto_mock.c
./PartoutOpenVPNConnection_C/control.c
./PartoutOpenVPNConnection_C/mss_fix.c
./PartoutOpenVPNConnection_C/dp_mode_ad.c
./PartoutOpenVPNConnection_C/dp_framing.c
./PartoutOpenVPNConnection_C/dp_mode.c
./PartoutOpenVPNConnection_C/logging.c
./PartoutOpenVPNConnection_C/pkt_proc.c
./PartoutCrypto/Native_C/src/mbed/keys.c
./PartoutCrypto/Native_C/src/mbed/tls.c
./PartoutCrypto/Native_C/src/crypto_stubs.c
./PartoutCrypto/Native_C/src/windows/hmac.c
./PartoutCrypto/Native_C/src/windows/crypto_ctr.c
./PartoutCrypto/Native_C/src/windows/crypto_cbc.c
./PartoutCrypto/Native_C/src/windows/crypto_aead.c
./PartoutCrypto/Native_C/src/windows/crypto.c
./PartoutCrypto/OpenSSL_C/hmac.c
./PartoutCrypto/OpenSSL_C/crypto_ctr.c
./PartoutCrypto/OpenSSL_C/crypto_cbc.c
./PartoutCrypto/OpenSSL_C/crypto_aead.c
./PartoutCrypto/OpenSSL_C/keys.c
./PartoutCrypto/OpenSSL_C/tls.c
./PartoutCrypto/OpenSSL_C/crypto.c
./MiniFoundation_C/std.c
./PartoutWireGuardConnection_C/wireguard.c
./PartoutCore_C/network.c
./PartoutCore_C/common.c
./PartoutCore_C/tunctrl.c
./PartoutCore_C/lib.c
./PartoutCore_C/tun_linux.c
./PartoutCore_C/tun_windows.c
./PartoutCore_C/tun_darwin.c
./PartoutCore_C/socket.c
./PartoutCore_C/zd.c
./PartoutCore_C/prng.c
./PartoutCore_C/tls_options.c
./PartoutCore_C/tun_android.c
)
