set(PARTOUT_SOURCES
./MiniFoundation/Core/EnumeratingRegex.swift
./MiniFoundation/Core/Expectation.swift
./MiniFoundation/Core/PRNG.swift
./MiniFoundation/Core/RandomlyInitialized.swift
./MiniFoundation/Core/UniqueID.swift
./MiniFoundation/Foundation/FileManager+Foundation.swift
./MiniFoundation/Foundation/NSObject+Stream.swift
./MiniFoundation/Foundation/Publisher+Stream.swift
./MiniFoundation/Foundation/RegularExpression+Foundation.swift
./MiniFoundation/Foundation/String+Foundation.swift
./MiniFoundation/FoundationCompat/CharacterSet.swift
./MiniFoundation/FoundationCompat/Error+Compat.swift
./MiniFoundation/FoundationCompat/FileBuffer.swift
./MiniFoundation/FoundationCompat/FileManager+Compat.swift
./MiniFoundation/FoundationCompat/NSLog.swift
./MiniFoundation/FoundationCompat/RegularExpression+Compat.swift
./MiniFoundation/FoundationCompat/String+Compat.swift
./MiniFoundation/FoundationEssentials/Data+Extensions.swift
./MiniFoundation/FoundationEssentials/Dictionary+Extensions.swift
./MiniFoundation/FoundationEssentials/FileManager+Extensions.swift
./MiniFoundation/FoundationEssentials/JSONCoder+Extensions.swift
./MiniFoundation/FoundationEssentials/String+Extensions.swift
./MiniFoundation/FoundationEssentials/URL+Extensions.swift
./MiniFoundation/JSON/Initialization.swift
./MiniFoundation/JSON/JSON.swift
./MiniFoundation/JSON/Merging.swift
./MiniFoundation/JSON/Querying.swift
./MiniFoundation/MiniFoundation.swift
./MiniFoundation/MiniFoundationError.swift
./MiniFoundation/Streams/AsyncStream+Extensions.swift
./MiniFoundation/Streams/CurrentValueStream.swift
./MiniFoundation/Streams/PassthroughStream.swift
./MiniFoundation/Streams/SubjectStream.swift
./Partout/Modules/ModuleHandler+Extensions.swift
./Partout/Modules/ModuleHandler.swift
./Partout/Modules/ModuleType+Extensions.swift
./Partout/Modules/TaggedModule.swift
./Partout/Modules/TaggedProfile.swift
./Partout/NativeHelpers.swift
./Partout/NativeTunnelController.swift
./Partout/PartoutExports.swift
./Partout/Registry+Support.swift
./Partout/Registry.swift
./Partout/Serialization/CodingRegistry.swift
./Partout/Serialization/LegacyProfileEncoderV2.swift
./Partout/Serialization/ProfileEncoderV3.swift
./Partout/VirtualTunnelInterface.swift
./PartoutCore/Connection/BSDSocket.swift
./PartoutCore/Connection/BSDSocketFactory.swift
./PartoutCore/Connection/BSDSocketObserver.swift
./PartoutCore/Connection/BetterPathBlock.swift
./PartoutCore/Connection/Connection.swift
./PartoutCore/Connection/ConnectionDaemon.swift
./PartoutCore/Connection/ConnectionParameters.swift
./PartoutCore/Connection/ConnectionStatus.swift
./PartoutCore/Connection/DNSResolver.swift
./PartoutCore/Connection/DataCount.swift
./PartoutCore/Connection/DummyReachabilityObserver.swift
./PartoutCore/Connection/EndpointResolver+Resolvable.swift
./PartoutCore/Connection/EndpointResolver.swift
./PartoutCore/Connection/IOInterface.swift
./PartoutCore/Connection/LinkInterface.swift
./PartoutCore/Connection/LinkObserver.swift
./PartoutCore/Connection/NetworkInterfaceFactory.swift
./PartoutCore/Connection/NetworkObserver.swift
./PartoutCore/Connection/POSIXDNSStrategy.swift
./PartoutCore/Connection/ReachabilityObserver.swift
./PartoutCore/Connection/SharedTunnelEnvironment.swift
./PartoutCore/Connection/SimpleConnectionDaemon.swift
./PartoutCore/Connection/SimpleDNSResolver.swift
./PartoutCore/Connection/SocketHandle.swift
./PartoutCore/Connection/SocketIOInterface.swift
./PartoutCore/Connection/StaticTunnelEnvironment.swift
./PartoutCore/Connection/TunnelController.swift
./PartoutCore/Connection/TunnelEnvironment.swift
./PartoutCore/Connection/TunnelEnvironmentKeys+Connection.swift
./PartoutCore/Connection/TunnelEnvironmentKeys.swift
./PartoutCore/Connection/TunnelRemoteInfo.swift
./PartoutCore/Data/CZeroingData+Shortcuts.swift
./PartoutCore/Data/CZeroingData.swift
./PartoutCore/Data/Data+Manipulation.swift
./PartoutCore/Data/Data+Network.swift
./PartoutCore/Data/Data+Zeroing.swift
./PartoutCore/Data/SecureData.swift
./PartoutCore/IP/Address.swift
./PartoutCore/IP/Endpoint.swift
./PartoutCore/IP/EndpointProtocol.swift
./PartoutCore/IP/ExtendedEndpoint+Socket.swift
./PartoutCore/IP/ExtendedEndpoint.swift
./PartoutCore/IP/IPHeader.swift
./PartoutCore/IP/IPSettings.swift
./PartoutCore/IP/Route.swift
./PartoutCore/IP/SocketType.swift
./PartoutCore/IP/Subnet.swift
./PartoutCore/Logging/DebugLog.swift
./PartoutCore/Logging/Encoder+Sensitive.swift
./PartoutCore/Logging/Foundation+Sensitive.swift
./PartoutCore/Logging/LocalLogger+FileStrategy.swift
./PartoutCore/Logging/LocalLogger.swift
./PartoutCore/Logging/LoggableModule.swift
./PartoutCore/Logging/LoggerCategory.swift
./PartoutCore/Logging/LoggerDestination.swift
./PartoutCore/Logging/PPLog.swift
./PartoutCore/Logging/PartoutLogger.swift
./PartoutCore/Logging/SensitiveDebugStringConvertible+Extensions.swift
./PartoutCore/Logging/SensitiveDebugStringConvertible.swift
./PartoutCore/Logging/SimpleLogDestination.swift
./PartoutCore/Misc/BidirectionalState.swift
./PartoutCore/Misc/DataUnit.swift
./PartoutCore/Misc/Keychain.swift
./PartoutCore/Misc/ScriptingEngine.swift
./PartoutCore/Misc/SemaphoreMutex.swift
./PartoutCore/Misc/Swift+Extensions.swift
./PartoutCore/Misc/Task+Extensions.swift
./PartoutCore/Misc/TimeInterval+Extensions.swift
./PartoutCore/Modules/CustomModule.swift
./PartoutCore/Modules/DNSModule.swift
./PartoutCore/Modules/DNSProtocol.swift
./PartoutCore/Modules/HTTPProxyModule.swift
./PartoutCore/Modules/IPModule.swift
./PartoutCore/Modules/OnDemandModule.swift
./PartoutCore/PRNG/PRNGProtocol+Suite.swift
./PartoutCore/PRNG/PRNGProtocol.swift
./PartoutCore/PRNG/PlatformPRNG.swift
./PartoutCore/PRNG/SimplePRNG.swift
./PartoutCore/Partout+Core.swift
./PartoutCore/PartoutConstants.swift
./PartoutCore/PartoutError.swift
./PartoutCore/Profile/Builder.swift
./PartoutCore/Profile/ConnectionModule.swift
./PartoutCore/Profile/Module+Defaults.swift
./PartoutCore/Profile/Module+Hashable.swift
./PartoutCore/Profile/Module.swift
./PartoutCore/Profile/ModuleBuilder.swift
./PartoutCore/Profile/ModuleType.swift
./PartoutCore/Profile/Profile+Diff.swift
./PartoutCore/Profile/Profile.swift
./PartoutCore/Profile/ProfileBehavior.swift
./PartoutCore/Profile/ProfileHeader.swift
./PartoutCore/Profile/ProfileType+Extensions.swift
./PartoutCore/Profile/ProfileType.swift
./PartoutCore/Registry/ConnectionFactory.swift
./PartoutCore/Registry/ModuleBuilderValidator.swift
./PartoutCore/Registry/ModuleImplementation.swift
./PartoutCore/Registry/ModuleImporter.swift
./PartoutCore/Registry/ModuleRegistry.swift
./PartoutCore/Registry/Resolver.swift
./PartoutCore/Serialization/CodingUserInfoKey+Modules.swift
./PartoutCore/Serialization/ConfigurationCoder.swift
./PartoutCore/Serialization/LegacyModuleDecoder.swift
./PartoutCore/Serialization/ProfileCoder.swift
./PartoutCore/Testing/MockDNSResolver.swift
./PartoutCore/Testing/MockLinkInterface.swift
./PartoutCore/Testing/MockNetworkInterfaceFactory.swift
./PartoutCore/Testing/MockTunnelController.swift
./PartoutCore/Testing/MockTunnelInterface.swift
./PartoutCore/Tunnel/DefaultMessageHandler.swift
./PartoutCore/Tunnel/FakeTunnelStrategy.swift
./PartoutCore/Tunnel/MessageHandler.swift
./PartoutCore/Tunnel/Tunnel.swift
./PartoutCore/Tunnel/TunnelSnapshot.swift
./PartoutCore/Tunnel/TunnelStatus.swift
./PartoutCore/Tunnel/TunnelStrategy.swift
./PartoutOS/Apple/AppleJavaScriptEngine.swift
./PartoutOS/Apple/AppleKeychain.swift
./PartoutOS/Apple/AppleRandom.swift
./PartoutOS/Apple/BundleConfiguration.swift
./PartoutOS/Apple/OSLogDestination.swift
./PartoutOS/Apple/PartoutTunnelObservable.swift
./PartoutOS/Apple/UserDefaultsEnvironment.swift
./PartoutOS/AppleNE/App/NETunnelEnvironment.swift
./PartoutOS/AppleNE/App/NETunnelManagerRepository.swift
./PartoutOS/AppleNE/App/NETunnelStrategy.swift
./PartoutOS/AppleNE/AppExtension/NEBetterPathBlock.swift
./PartoutOS/AppleNE/AppExtension/NEObservablePath.swift
./PartoutOS/AppleNE/AppExtension/NEPTPForwarder.swift
./PartoutOS/AppleNE/AppExtension/NESettingsApplying.swift
./PartoutOS/AppleNE/AppExtension/NESettingsModule.swift
./PartoutOS/AppleNE/Connection/NEInterfaceFactory.swift
./PartoutOS/AppleNE/Connection/NETCPSocket.swift
./PartoutOS/AppleNE/Connection/NETunnelController.swift
./PartoutOS/AppleNE/Connection/NETunnelInterface.swift
./PartoutOS/AppleNE/Connection/NEUDPSocket.swift
./PartoutOS/AppleNE/Connection/ValueObserver.swift
./PartoutOS/AppleNE/Extensions/Module+Requirements.swift
./PartoutOS/AppleNE/Extensions/NE+Hacks.swift
./PartoutOS/AppleNE/Extensions/NEIPv4Route+Equatable.swift
./PartoutOS/AppleNE/Extensions/NEIPv4Settings+DebugDescription.swift
./PartoutOS/AppleNE/Extensions/NEIPv6Route+Equatable.swift
./PartoutOS/AppleNE/Extensions/NEIPv6Settings+DebugDescription.swift
./PartoutOS/AppleNE/Extensions/NEOnDemandRule+Equatable.swift
./PartoutOS/AppleNE/Extensions/NWConnectionState+Description.swift
./PartoutOS/AppleNE/Extensions/NWTCPConnectionState+Description.swift
./PartoutOS/AppleNE/Extensions/NWUDPSessionState+Description.swift
./PartoutOS/AppleNE/Extensions/OnDemandModule+Support.swift
./PartoutOS/AppleNE/Modules/DNSModule+NE.swift
./PartoutOS/AppleNE/Modules/HTTPProxyModule+NE.swift
./PartoutOS/AppleNE/Modules/IPModule+NE.swift
./PartoutOS/AppleNE/Modules/OnDemandModule+NE.swift
./PartoutOS/AppleNE/Modules/Profile+NE.swift
./PartoutOS/AppleNE/Serialization/KeychainNEProtocolCoder.swift
./PartoutOS/AppleNE/Serialization/NEProtocolCoder.swift
./PartoutOS/AppleNE/Serialization/ProviderNEProtocolCoder.swift
./PartoutOS/Partout+OS.swift
./PartoutOpenVPN/CompressionAlgorithm.swift
./PartoutOpenVPN/CompressionFraming.swift
./PartoutOpenVPN/Credentials.swift
./PartoutOpenVPN/CryptoContainer.swift
./PartoutOpenVPN/KeyDecrypter.swift
./PartoutOpenVPN/ObfuscationMethod.swift
./PartoutOpenVPN/OpenVPN+Configuration.swift
./PartoutOpenVPN/OpenVPN+Serialization.swift
./PartoutOpenVPN/OpenVPN.swift
./PartoutOpenVPN/OpenVPNModule+Implementation.swift
./PartoutOpenVPN/OpenVPNModule.swift
./PartoutOpenVPN/OpenVPNOption.swift
./PartoutOpenVPN/Partout+OpenVPN.swift
./PartoutOpenVPN/StandardOpenVPNParser+Builder.swift
./PartoutOpenVPN/StandardOpenVPNParser.swift
./PartoutOpenVPN/StandardOpenVPNParserError.swift
./PartoutOpenVPN/StaticKey.swift
./PartoutOpenVPN/TLSWrap.swift
./PartoutOpenVPNConnection/Internal/Aliases+Cross.swift
./PartoutOpenVPNConnection/Internal/AuthSerializer.swift
./PartoutOpenVPNConnection/Internal/Authenticator.swift
./PartoutOpenVPNConnection/Internal/CControlPacket+Serialization.swift
./PartoutOpenVPNConnection/Internal/CControlPacket.swift
./PartoutOpenVPNConnection/Internal/CDataPath.swift
./PartoutOpenVPNConnection/Internal/CPacketCode.swift
./PartoutOpenVPNConnection/Internal/CPacketProtocol.swift
./PartoutOpenVPNConnection/Internal/CZeroingData+HMAC.swift
./PartoutOpenVPNConnection/Internal/Constants.swift
./PartoutOpenVPNConnection/Internal/ControlChannel+Cross.swift
./PartoutOpenVPNConnection/Internal/ControlChannel.swift
./PartoutOpenVPNConnection/Internal/ControlChannelSerializer.swift
./PartoutOpenVPNConnection/Internal/CryptSerializer.swift
./PartoutOpenVPNConnection/Internal/CryptV2Serializer.swift
./PartoutOpenVPNConnection/Internal/CryptoError.swift
./PartoutOpenVPNConnection/Internal/CryptoFactories.swift
./PartoutOpenVPNConnection/Internal/CryptoKeys+PRF.swift
./PartoutOpenVPNConnection/Internal/CryptoKeys.swift
./PartoutOpenVPNConnection/Internal/DataChannel.swift
./PartoutOpenVPNConnection/Internal/DataPathError.swift
./PartoutOpenVPNConnection/Internal/DataPathProtocol.swift
./PartoutOpenVPNConnection/Internal/DataPathWrapper+Native.swift
./PartoutOpenVPNConnection/Internal/DataPathWrapper.swift
./PartoutOpenVPNConnection/Internal/Error+Recoverable.swift
./PartoutOpenVPNConnection/Internal/ExtendedEndpoint+Random.swift
./PartoutOpenVPNConnection/Internal/Handshake.swift
./PartoutOpenVPNConnection/Internal/NegotiationHistory.swift
./PartoutOpenVPNConnection/Internal/Negotiator.swift
./PartoutOpenVPNConnection/Internal/NetworkSettingsBuilder.swift
./PartoutOpenVPNConnection/Internal/OCCPacket.swift
./PartoutOpenVPNConnection/Internal/OpenVPNActor.swift
./PartoutOpenVPNConnection/Internal/OpenVPNConfiguration+CipherNegotiation.swift
./PartoutOpenVPNConnection/Internal/OpenVPNErrorCode+Cross.swift
./PartoutOpenVPNConnection/Internal/OpenVPNSession+Data.swift
./PartoutOpenVPNConnection/Internal/OpenVPNSession+Loop.swift
./PartoutOpenVPNConnection/Internal/OpenVPNSession+Negotiation.swift
./PartoutOpenVPNConnection/Internal/OpenVPNSession.swift
./PartoutOpenVPNConnection/Internal/OpenVPNSessionError+Mapping.swift
./PartoutOpenVPNConnection/Internal/OpenVPNSessionError.swift
./PartoutOpenVPNConnection/Internal/OpenVPNSessionProtocol.swift
./PartoutOpenVPNConnection/Internal/OpenVPNTCPLink.swift
./PartoutOpenVPNConnection/Internal/OpenVPNUDPLink.swift
./PartoutOpenVPNConnection/Internal/PIAHardReset.swift
./PartoutOpenVPNConnection/Internal/PacketProcessor.swift
./PartoutOpenVPNConnection/Internal/PlainSerializer.swift
./PartoutOpenVPNConnection/Internal/PushReply.swift
./PartoutOpenVPNConnection/Internal/RenegotiationType.swift
./PartoutOpenVPNConnection/Internal/ServerOCC.swift
./PartoutOpenVPNConnection/Internal/SimpleKeyDecrypter.swift
./PartoutOpenVPNConnection/Internal/TLSError.swift
./PartoutOpenVPNConnection/Internal/TLSProtocol.swift
./PartoutOpenVPNConnection/Internal/TLSWrapper+Native.swift
./PartoutOpenVPNConnection/Internal/TLSWrapper.swift
./PartoutOpenVPNConnection/OpenVPNConnection+Alias.swift
./PartoutOpenVPNConnection/OpenVPNConnectionOptions.swift
./PartoutOpenVPNConnection/StandardOpenVPNParser+Default.swift
./PartoutOpenVPNConnection/V2/_OpenVPNConnectionV2+Default.swift
./PartoutOpenVPNConnection/V2/_OpenVPNConnectionV2.swift
./PartoutWireGuard/Internal/Configuration+WgQuickConfig.swift
./PartoutWireGuard/Internal/Endpoint+WireGuardKit.swift
./PartoutWireGuard/Internal/PrivateKey.swift
./PartoutWireGuard/Internal/String+ArrayConversion.swift
./PartoutWireGuard/Key.swift
./PartoutWireGuard/LocalInterface.swift
./PartoutWireGuard/Partout+WireGuard.swift
./PartoutWireGuard/RemoteInterface.swift
./PartoutWireGuard/StandardWireGuardKeyGenerator.swift
./PartoutWireGuard/StandardWireGuardParser+Validate.swift
./PartoutWireGuard/StandardWireGuardParser.swift
./PartoutWireGuard/WireGuard+Configuration.swift
./PartoutWireGuard/WireGuard.swift
./PartoutWireGuard/WireGuardKeyGenerator.swift
./PartoutWireGuard/WireGuardModule+Implementation.swift
./PartoutWireGuard/WireGuardModule.swift
./PartoutWireGuard/WireGuardParseError.swift
./PartoutWireGuardConnection/Internal/WireGuardBackend.swift
./PartoutWireGuardConnection/V2/Internal/Configuration+Resolve.swift
./PartoutWireGuardConnection/V2/Internal/String+Base64Hex.swift
./PartoutWireGuardConnection/V2/Internal/TunnelRemoteInfoGenerator.swift
./PartoutWireGuardConnection/V2/Internal/WireGuardAdapter.swift
./PartoutWireGuardConnection/V2/Internal/WireGuardAdapterError.swift
./PartoutWireGuardConnection/V2/_WireGuardConnectionV2.swift
./PartoutWireGuardConnection/WireGuardConnection+Alias.swift
)
set(PARTOUT_C_SOURCES
./MiniFoundation_C/rx.cc
./MiniFoundation_C/std.c
./PartoutCore_C/common.c
./PartoutCore_C/lib.c
./PartoutCore_C/network.c
./PartoutCore_C/prng.c
./PartoutCore_C/socket.c
./PartoutCore_C/tls_options.c
./PartoutCore_C/tun_android.c
./PartoutCore_C/tun_darwin.c
./PartoutCore_C/tun_dummy.c
./PartoutCore_C/tun_linux.c
./PartoutCore_C/tun_windows.c
./PartoutCore_C/zd.c
./PartoutCrypto/Native_C/src/crypto_stubs.c
./PartoutCrypto/Native_C/src/mbed/keys.c
./PartoutCrypto/Native_C/src/mbed/tls.c
./PartoutCrypto/Native_C/src/windows/crypto.c
./PartoutCrypto/Native_C/src/windows/crypto_aead.c
./PartoutCrypto/Native_C/src/windows/crypto_cbc.c
./PartoutCrypto/Native_C/src/windows/crypto_ctr.c
./PartoutCrypto/Native_C/src/windows/hmac.c
./PartoutCrypto/OpenSSL_C/crypto.c
./PartoutCrypto/OpenSSL_C/crypto_aead.c
./PartoutCrypto/OpenSSL_C/crypto_cbc.c
./PartoutCrypto/OpenSSL_C/crypto_ctr.c
./PartoutCrypto/OpenSSL_C/hmac.c
./PartoutCrypto/OpenSSL_C/keys.c
./PartoutCrypto/OpenSSL_C/tls.c
./PartoutOpenVPNConnection_C/control.c
./PartoutOpenVPNConnection_C/dp_framing.c
./PartoutOpenVPNConnection_C/dp_mode.c
./PartoutOpenVPNConnection_C/dp_mode_ad.c
./PartoutOpenVPNConnection_C/dp_mode_hmac.c
./PartoutOpenVPNConnection_C/logging.c
./PartoutOpenVPNConnection_C/mss_fix.c
./PartoutOpenVPNConnection_C/pkt_proc.c
./PartoutOpenVPNConnection_C/test/crypto_mock.c
./PartoutWireGuardConnection_C/wireguard.c
./PartoutWireGuard_C/key.c
./PartoutWireGuard_C/logging.c
./PartoutWireGuard_C/x25519.c
)
