//
// ABIErrorPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct ABIErrorPayload: Sendable, Codable, Hashable {

    public let code: PartoutErrorCode
    public let userInfo: JSON?

    public init(code: PartoutErrorCode, userInfo: JSON? = nil) {
        self.code = code
        self.userInfo = userInfo
    }
}

