//
// DataCount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** A pair of received/sent bytes count. */
public struct DataCount: Sendable, Codable, Hashable {

    /** Received bytes count. */
    public let received: ModelUInt64
    /** Sent bytes count. */
    public let sent: ModelUInt64

    public init(received: ModelUInt64, sent: ModelUInt64) {
        self.received = received
        self.sent = sent
    }
}

