//
// DNSModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** DNS settings. */
public struct DNSModule: Sendable, Codable, Hashable {

    public let id: UniqueID
    public let protocolType: DNSModuleProtocolType
    public let servers: [Address]
    public let domainName: Address?
    public let searchDomains: [Address]?
    public let inheritsVPN: Bool?
    public let domainPolicy: DNSModuleDomainPolicy?
    public let routesThroughVPN: Bool?

    public init(id: UniqueID, protocolType: DNSModuleProtocolType, servers: [Address], domainName: Address? = nil, searchDomains: [Address]? = nil, inheritsVPN: Bool? = nil, domainPolicy: DNSModuleDomainPolicy? = nil, routesThroughVPN: Bool? = nil) {
        self.id = id
        self.protocolType = protocolType
        self.servers = servers
        self.domainName = domainName
        self.searchDomains = searchDomains
        self.inheritsVPN = inheritsVPN
        self.domainPolicy = domainPolicy
        self.routesThroughVPN = routesThroughVPN
    }
}

