//
// DNSModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** DNS settings. */
public struct DNSModule: Sendable, Codable, Hashable {

    public let domainName: Address?
    public let domainPolicy: DNSModuleDomainPolicy?
    public let id: UniqueID
    public let inheritsVPN: Bool?
    public let protocolType: DNSModuleProtocolType
    public let routesThroughVPN: Bool?
    public let searchDomains: [Address]?
    public let servers: [Address]

    public init(domainName: Address? = nil, domainPolicy: DNSModuleDomainPolicy? = nil, id: UniqueID, inheritsVPN: Bool? = nil, protocolType: DNSModuleProtocolType, routesThroughVPN: Bool? = nil, searchDomains: [Address]? = nil, servers: [Address]) {
        self.domainName = domainName
        self.domainPolicy = domainPolicy
        self.id = id
        self.inheritsVPN = inheritsVPN
        self.protocolType = protocolType
        self.routesThroughVPN = routesThroughVPN
        self.searchDomains = searchDomains
        self.servers = servers
    }
}

