//
// DNSModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


/** DNS settings. */
public struct DNSModule: Codable, Hashable {

    public var domainName: Address?
    public var domainPolicy: DNSModuleDomainPolicy?
    public var id: UniqueID
    public var inheritsVPN: Bool?
    public var protocolType: DNSModuleProtocolType
    public var routesThroughVPN: Bool?
    public var searchDomains: [Address]?
    public var servers: [Address]

    public init(domainName: Address? = nil, domainPolicy: DNSModuleDomainPolicy? = nil, id: UniqueID, inheritsVPN: Bool? = nil, protocolType: DNSModuleProtocolType, routesThroughVPN: Bool? = nil, searchDomains: [Address]? = nil, servers: [Address]) {
        self.domainName = domainName
        self.domainPolicy = domainPolicy
        self.id = id
        self.inheritsVPN = inheritsVPN
        self.protocolType = protocolType
        self.routesThroughVPN = routesThroughVPN
        self.searchDomains = searchDomains
        self.servers = servers
    }

}


