//
// DNSModuleProtocolTypeCleartext.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct DNSModuleProtocolTypeCleartext: Codable, Hashable, Sendable {

    public enum ModelType: String, Codable, CaseIterable, Sendable {
        case cleartext = "cleartext"
    }
    public var type: ModelType

    public init(type: ModelType) {
        self.type = type
    }
}

