//
// DNSModuleProtocolTypeCleartext.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


public struct DNSModuleProtocolTypeCleartext: Codable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case cleartext = "cleartext"
    }
    public var type: ModelType

    public init(type: ModelType) {
        self.type = type
    }

}


