//
// DNSModuleProtocolTypeHttps.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


public struct DNSModuleProtocolTypeHttps: Codable, Hashable, Sendable {

    public enum ModelType: String, Codable, CaseIterable, Sendable {
        case https = "https"
    }

    public var type: ModelType
    public var url: URL

    public init(type: ModelType, url: URL) {
        self.type = type
        self.url = url
    }

}


