//
// DNSModuleProtocolTypeTls.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


public struct DNSModuleProtocolTypeTls: Codable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case tls = "tls"
    }
    public var type: ModelType
    public var hostname: String

    public init(type: ModelType, hostname: String) {
        self.type = type
        self.hostname = hostname
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case hostname
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(hostname, forKey: .hostname)
    }
}


