//
// DNSProtocol.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** The protocol used in DNS servers. */
public enum DNSProtocol: String, Codable, CaseIterable, Sendable {
    /// The value to fall back to when unset. Standard cleartext DNS (port 53).
    case cleartext = "cleartext"
    /// DNS over HTTPS.
    case https = "https"
    /// DNS over TLS (port 853).
    case tls = "tls"
}
