//
// HTTPProxyModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


/** HTTP proxy settings. */
public struct HTTPProxyModule: Codable, Hashable {

    public var bypassDomains: [Address]
    public var id: UniqueID
    public var pacURL: URL?
    public var proxy: Endpoint?
    public var secureProxy: Endpoint?

    public init(bypassDomains: [Address], id: UniqueID, pacURL: URL? = nil, proxy: Endpoint? = nil, secureProxy: Endpoint? = nil) {
        self.bypassDomains = bypassDomains
        self.id = id
        self.pacURL = pacURL
        self.proxy = proxy
        self.secureProxy = secureProxy
    }

}


