//
// HTTPProxyModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** HTTP proxy settings. */
public struct HTTPProxyModule: Sendable, Codable, Hashable {

    public let bypassDomains: [Address]
    public let id: UniqueID
    public let pacURL: URL?
    public let proxy: Endpoint?
    public let secureProxy: Endpoint?

    public init(bypassDomains: [Address], id: UniqueID, pacURL: URL? = nil, proxy: Endpoint? = nil, secureProxy: Endpoint? = nil) {
        self.bypassDomains = bypassDomains
        self.id = id
        self.pacURL = pacURL
        self.proxy = proxy
        self.secureProxy = secureProxy
    }
}

