//
// IPModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** IP and routes. */
public struct IPModule: Sendable, Codable, Hashable {

    public let id: UniqueID
    public let ipv4: IPSettings?
    public let ipv6: IPSettings?
    public let mtu: Int?

    public init(id: UniqueID, ipv4: IPSettings? = nil, ipv6: IPSettings? = nil, mtu: Int? = nil) {
        self.id = id
        self.ipv4 = ipv4
        self.ipv6 = ipv6
        self.mtu = mtu
    }
}

