//
// IPSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


/** IP settings and routes. */
public struct IPSettings: Codable, Hashable {

    /** The excluded routes. */
    public var excludedRoutes: [Route]
    /** The included routes. */
    public var includedRoutes: [Route]
    /** The subnets. */
    public var subnets: [Subnet]

    public init(excludedRoutes: [Route], includedRoutes: [Route], subnets: [Subnet]) {
        self.excludedRoutes = excludedRoutes
        self.includedRoutes = includedRoutes
        self.subnets = subnets
    }

}


