//
// OnDemandModuleOtherNetwork.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public enum OnDemandModuleOtherNetwork: String, Codable, CaseIterable, Sendable {
    case mobile = "mobile"
    case ethernet = "ethernet"
}
