//
// OnDemandModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** On-demand settings. */
public struct OnDemandModule: Sendable, Codable, Hashable {
    public let id: UniqueID
    public let policy: OnDemandModulePolicy
    public let withOtherNetworks: Set<OnDemandModuleOtherNetwork>
    public let withSSIDs: [String: Bool]

    public init(id: UniqueID, policy: OnDemandModulePolicy, withOtherNetworks: Set<OnDemandModuleOtherNetwork>, withSSIDs: [String: Bool]) {
        self.id = id
        self.policy = policy
        self.withOtherNetworks = withOtherNetworks
        self.withSSIDs = withSSIDs
    }
}

