//
// OnDemandModuleOtherNetwork.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


public enum OnDemandModuleOtherNetwork: String, Codable, CaseIterable {
    case mobile = "mobile"
    case ethernet = "ethernet"
}

