//
// OnDemandModulePolicy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


public enum OnDemandModulePolicy: String, Codable, CaseIterable {
    case any = "any"
    case including = "including"
    case excluding = "excluding"
}

