//
// OnDemandModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** On-demand settings. */
public struct OnDemandModule: Sendable, Codable, Hashable {
    public let id: UniqueID
    public let policy: OnDemandModulePolicy
    public let withSSIDs: [String: Bool]
    public let withOtherNetworks: Set<OnDemandModuleOtherNetwork>

    public init(id: UniqueID, policy: OnDemandModulePolicy, withSSIDs: [String: Bool], withOtherNetworks: Set<OnDemandModuleOtherNetwork>) {
        self.id = id
        self.policy = policy
        self.withSSIDs = withSSIDs
        self.withOtherNetworks = withOtherNetworks
    }
}

