//
// OnDemandModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


/** On-demand settings. */
public struct OnDemandModule: Codable, Hashable, Sendable {

    public var id: UniqueID
    public var policy: OnDemandModulePolicy
    public var withOtherNetworks: Set<OnDemandModuleOtherNetwork>
    public var withSSIDs: [String: Bool]

    public init(id: UniqueID, policy: OnDemandModulePolicy, withOtherNetworks: Set<OnDemandModuleOtherNetwork>, withSSIDs: [String: Bool]) {
        self.id = id
        self.policy = policy
        self.withOtherNetworks = withOtherNetworks
        self.withSSIDs = withSSIDs
    }

}


