//
// OpenVPNModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


/** A connection module providing an OpenVPN connection. */
public struct OpenVPNModule: Codable, Hashable, Sendable {

    public var configuration: OpenVPNConfiguration?
    public var credentials: OpenVPNCredentials?
    public var id: UniqueID
    public var requiresInteractiveCredentials: Bool?

    public init(configuration: OpenVPNConfiguration? = nil, credentials: OpenVPNCredentials? = nil, id: UniqueID, requiresInteractiveCredentials: Bool? = nil) {
        self.configuration = configuration
        self.credentials = credentials
        self.id = id
        self.requiresInteractiveCredentials = requiresInteractiveCredentials
    }

}


