//
// OpenVPNCredentials.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** A set of credentials for authentication. */
public struct OpenVPNCredentials: Sendable, Codable, Hashable {

    /** The username. */
    public let username: String
    /** The password. */
    public let password: String
    /** The OTP method (defaults to ``OTPMethod-swift.enum/none``). */
    public let otpMethod: OpenVPNCredentialsOTPMethod
    /** The OTP. */
    public let otp: String?

    public init(username: String, password: String, otpMethod: OpenVPNCredentialsOTPMethod, otp: String? = nil) {
        self.username = username
        self.password = password
        self.otpMethod = otpMethod
        self.otp = otp
    }
}

