//
// OpenVPNObfuscationMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


/** The obfuscation method. */
public struct OpenVPNObfuscationMethod: Codable, Hashable {

    public var type: String

    public init(type: String) {
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
    }
}


