//
// OpenVPNObfuscationMethodReverse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct OpenVPNObfuscationMethodReverse: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case reverse = "reverse"
    }
    public let type: ModelType

    public init(type: ModelType) {
        self.type = type
    }
}

