//
// OpenVPNConfiguration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** The immutable configuration for `OpenVPNSession`. */
public struct OpenVPNConfiguration: Sendable, Codable, Hashable {

    /** - Seealso: `Configuration.Builder.cipher` */
    public let cipher: OpenVPNCipher?
    /** - Seealso: `Configuration.Builder.dataCiphers` */
    public let dataCiphers: [OpenVPNCipher]?
    /** - Seealso: `Configuration.Builder.digest` */
    public let digest: OpenVPNDigest?
    /** - Seealso: `Configuration.Builder.compressionFraming` */
    public let compressionFraming: OpenVPNCompressionFraming?
    /** - Seealso: `Configuration.Builder.compressionAlgorithm` */
    public let compressionAlgorithm: OpenVPNCompressionAlgorithm?
    /** - Seealso: `Configuration.Builder.ca` */
    public let ca: OpenVPNCryptoContainer?
    /** - Seealso: `Configuration.Builder.clientCertificate` */
    public let clientCertificate: OpenVPNCryptoContainer?
    /** - Seealso: `Configuration.Builder.clientKey` */
    public let clientKey: OpenVPNCryptoContainer?
    /** - Seealso: `Configuration.Builder.tlsWrap` */
    public let tlsWrap: OpenVPNTLSWrap?
    /** - Seealso: `Configuration.Builder.tlsSecurityLevel` */
    public let tlsSecurityLevel: Int?
    /** - Seealso: `Configuration.Builder.keepAliveInterval` */
    public let keepAliveInterval: Double?
    /** - Seealso: `Configuration.Builder.keepAliveTimeout` */
    public let keepAliveTimeout: Double?
    /** - Seealso: `Configuration.Builder.renegotiatesAfter` */
    public let renegotiatesAfter: Double?
    /** - Seealso: `Configuration.Builder.remotes` */
    public let remotes: [ExtendedEndpoint]?
    /** - Seealso: `Configuration.Builder.checksEKU` */
    public let checksEKU: Bool?
    /** - Seealso: `Configuration.Builder.checksSANHost` */
    public let checksSANHost: Bool?
    /** - Seealso: `Configuration.Builder.sanHost` */
    public let sanHost: String?
    /** - Seealso: `Configuration.Builder.randomizeEndpoint` */
    public let randomizeEndpoint: Bool?
    /** - Seealso: `Configuration.Builder.randomizeHostnames` */
    public let randomizeHostnames: Bool?
    /** - Seealso: `Configuration.Builder.usesPIAPatches` */
    public let usesPIAPatches: Bool?
    /** - Seealso: `Configuration.Builder.mtu` */
    public let mtu: Int?
    /** - Seealso: `Configuration.Builder.authUserPass` */
    public let authUserPass: Bool?
    /** - Seealso: `Configuration.Builder.staticChallenge` */
    public let staticChallenge: Bool?
    /** - Seealso: `Configuration.Builder.authToken` */
    public let authToken: String?
    /** - Seealso: `Configuration.Builder.peerId` */
    public let peerId: ModelUInt32?
    /** - Seealso: `Configuration.Builder.ipv4` */
    public let ipv4: IPSettings?
    /** - Seealso: `Configuration.Builder.ipv6` */
    public let ipv6: IPSettings?
    /** - Seealso: `Configuration.Builder.routes4` */
    public let routes4: [Route]?
    /** - Seealso: `Configuration.Builder.routes6` */
    public let routes6: [Route]?
    /** - Seealso: `Configuration.Builder.routeGateway4` */
    public let routeGateway4: Address?
    /** - Seealso: `Configuration.Builder.routeGateway6` */
    public let routeGateway6: Address?
    /** - Seealso: `Configuration.Builder.dnsServers` */
    public let dnsServers: [String]?
    /** - Seealso: `Configuration.Builder.dnsDomain` */
    public let dnsDomain: String?
    /** - Seealso: `Configuration.Builder.searchDomains` */
    public let searchDomains: [String]?
    /** - Seealso: `Configuration.Builder.httpProxy` */
    public let httpProxy: Endpoint?
    /** - Seealso: `Configuration.Builder.httpsProxy` */
    public let httpsProxy: Endpoint?
    /** - Seealso: `Configuration.Builder.proxyAutoConfigurationURL` */
    public let proxyAutoConfigurationURL: URL?
    /** - Seealso: `Configuration.Builder.proxyBypassDomains` */
    public let proxyBypassDomains: [String]?
    /** - Seealso: `Configuration.Builder.routingPolicies` */
    public let routingPolicies: [OpenVPNRoutingPolicy]?
    /** - Seealso: `Configuration.Builder.noPullMask` */
    public let noPullMask: [OpenVPNPullMask]?
    /** - Seealso: `Configuration.Builder.xorMethod` */
    public let xorMethod: OpenVPNObfuscationMethod?

    public init(cipher: OpenVPNCipher? = nil, dataCiphers: [OpenVPNCipher]? = nil, digest: OpenVPNDigest? = nil, compressionFraming: OpenVPNCompressionFraming? = nil, compressionAlgorithm: OpenVPNCompressionAlgorithm? = nil, ca: OpenVPNCryptoContainer? = nil, clientCertificate: OpenVPNCryptoContainer? = nil, clientKey: OpenVPNCryptoContainer? = nil, tlsWrap: OpenVPNTLSWrap? = nil, tlsSecurityLevel: Int? = nil, keepAliveInterval: Double? = nil, keepAliveTimeout: Double? = nil, renegotiatesAfter: Double? = nil, remotes: [ExtendedEndpoint]? = nil, checksEKU: Bool? = nil, checksSANHost: Bool? = nil, sanHost: String? = nil, randomizeEndpoint: Bool? = nil, randomizeHostnames: Bool? = nil, usesPIAPatches: Bool? = nil, mtu: Int? = nil, authUserPass: Bool? = nil, staticChallenge: Bool? = nil, authToken: String? = nil, peerId: ModelUInt32? = nil, ipv4: IPSettings? = nil, ipv6: IPSettings? = nil, routes4: [Route]? = nil, routes6: [Route]? = nil, routeGateway4: Address? = nil, routeGateway6: Address? = nil, dnsServers: [String]? = nil, dnsDomain: String? = nil, searchDomains: [String]? = nil, httpProxy: Endpoint? = nil, httpsProxy: Endpoint? = nil, proxyAutoConfigurationURL: URL? = nil, proxyBypassDomains: [String]? = nil, routingPolicies: [OpenVPNRoutingPolicy]? = nil, noPullMask: [OpenVPNPullMask]? = nil, xorMethod: OpenVPNObfuscationMethod? = nil) {
        self.cipher = cipher
        self.dataCiphers = dataCiphers
        self.digest = digest
        self.compressionFraming = compressionFraming
        self.compressionAlgorithm = compressionAlgorithm
        self.ca = ca
        self.clientCertificate = clientCertificate
        self.clientKey = clientKey
        self.tlsWrap = tlsWrap
        self.tlsSecurityLevel = tlsSecurityLevel
        self.keepAliveInterval = keepAliveInterval
        self.keepAliveTimeout = keepAliveTimeout
        self.renegotiatesAfter = renegotiatesAfter
        self.remotes = remotes
        self.checksEKU = checksEKU
        self.checksSANHost = checksSANHost
        self.sanHost = sanHost
        self.randomizeEndpoint = randomizeEndpoint
        self.randomizeHostnames = randomizeHostnames
        self.usesPIAPatches = usesPIAPatches
        self.mtu = mtu
        self.authUserPass = authUserPass
        self.staticChallenge = staticChallenge
        self.authToken = authToken
        self.peerId = peerId
        self.ipv4 = ipv4
        self.ipv6 = ipv6
        self.routes4 = routes4
        self.routes6 = routes6
        self.routeGateway4 = routeGateway4
        self.routeGateway6 = routeGateway6
        self.dnsServers = dnsServers
        self.dnsDomain = dnsDomain
        self.searchDomains = searchDomains
        self.httpProxy = httpProxy
        self.httpsProxy = httpsProxy
        self.proxyAutoConfigurationURL = proxyAutoConfigurationURL
        self.proxyBypassDomains = proxyBypassDomains
        self.routingPolicies = routingPolicies
        self.noPullMask = noPullMask
        self.xorMethod = xorMethod
    }
}

