//
// OpenVPNObfuscationMethodXormask.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct OpenVPNObfuscationMethodXormask: Codable, Hashable, Sendable {

    public enum ModelType: String, Codable, CaseIterable, Sendable {
        case xormask = "xormask"
    }
    public var type: ModelType
    public var mask: SecureData

    public init(type: ModelType, mask: SecureData) {
        self.type = type
        self.mask = mask
    }
}

