//
// OpenVPNObfuscationMethodReverse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


public struct OpenVPNObfuscationMethodReverse: Codable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case reverse = "reverse"
    }
    public var type: ModelType

    public init(type: ModelType) {
        self.type = type
    }

}


