//
// OpenVPNCredentials.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** A set of credentials for authentication. */
public struct OpenVPNCredentials: Sendable, Codable, Hashable {

    /** The OTP. */
    public let otp: String?
    /** The OTP method (defaults to ``OTPMethod-swift.enum/none``). */
    public let otpMethod: OpenVPNCredentialsOTPMethod
    /** The password. */
    public let password: String
    /** The username. */
    public let username: String

    public init(otp: String? = nil, otpMethod: OpenVPNCredentialsOTPMethod, password: String, username: String) {
        self.otp = otp
        self.otpMethod = otpMethod
        self.password = password
        self.username = username
    }
}

