//
// OpenVPNObfuscationMethodXorptrpos.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


public struct OpenVPNObfuscationMethodXorptrpos: Codable, Hashable, Sendable {

    public enum ModelType: String, Codable, CaseIterable, Sendable {
        case xorptrpos = "xorptrpos"
    }

    public var type: ModelType

    public init(type: ModelType) {
        self.type = type
    }

}


