//
// OpenVPNTLSWrap.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


/** Holds parameters for TLS wrapping. */
public struct OpenVPNTLSWrap: Codable, Hashable {

    /** The static encryption key. */
    public var key: OpenVPNStaticKey
    /** The wrapping strategy. */
    public var strategy: OpenVPNTLSWrapStrategy
    /** The wrapped client key appended to initial tls-crypt-v2 packets. */
    public var wrappedKey: SecureData?

    public init(key: OpenVPNStaticKey, strategy: OpenVPNTLSWrapStrategy, wrappedKey: SecureData? = nil) {
        self.key = key
        self.strategy = strategy
        self.wrappedKey = wrappedKey
    }

}


