//
// OpenVPNObfuscationMethodXorptrpos.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


public struct OpenVPNObfuscationMethodXorptrpos: Codable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case xorptrpos = "xorptrpos"
    }
    public var type: ModelType

    public init(type: ModelType) {
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
    }
}


