//
// OpenVPNObfuscationMethodXorptrpos.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


public struct OpenVPNObfuscationMethodXorptrpos: Codable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case xorptrpos = "xorptrpos"
    }
    public var type: ModelType

    public init(type: ModelType) {
        self.type = type
    }

}


