//
// ProfileBehavior.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** Advanced flags affecting the behavior of a ``Profile``. */
public struct ProfileBehavior: Sendable, Codable, Hashable {

    /** Disconnects when the device goes to sleep. */
    public let disconnectsOnSleep: Bool
    /** Attempts to route as much traffic as possible through the tunnel. */
    public let includesAllNetworks: Bool?

    public init(disconnectsOnSleep: Bool, includesAllNetworks: Bool? = nil) {
        self.disconnectsOnSleep = disconnectsOnSleep
        self.includesAllNetworks = includesAllNetworks
    }
}

