//
// Route.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


/** Represents a route in the routing table. */
public struct Route: Codable, Hashable {

    /** The destination subnet or `nil` if default. */
    public var destination: String?
    /** The address of the gateway (falls back to global gateway). */
    public var gateway: String?

    public init(destination: String? = nil, gateway: String? = nil) {
        self.destination = destination
        self.gateway = gateway
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case destination
        case gateway
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(destination, forKey: .destination)
        try container.encodeIfPresent(gateway, forKey: .gateway)
    }
}


