//
// TaggedProfile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


/** A codable wrapper for a profile with all known modules. */
public struct TaggedProfile: Codable, Hashable {

    public var activeModulesIds: Set<UniqueID>
    public var behavior: ProfileBehavior?
    public var id: UniqueID
    public var modules: [TaggedModule]
    public var name: String
    public var userInfo: JSON?
    public var version: Int?

    public init(activeModulesIds: Set<UniqueID>, behavior: ProfileBehavior? = nil, id: UniqueID, modules: [TaggedModule], name: String, userInfo: JSON? = nil, version: Int? = nil) {
        self.activeModulesIds = activeModulesIds
        self.behavior = behavior
        self.id = id
        self.modules = modules
        self.name = name
        self.userInfo = userInfo
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case activeModulesIds
        case behavior
        case id
        case modules
        case name
        case userInfo
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(activeModulesIds, forKey: .activeModulesIds)
        try container.encodeIfPresent(behavior, forKey: .behavior)
        try container.encode(id, forKey: .id)
        try container.encode(modules, forKey: .modules)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(userInfo, forKey: .userInfo)
        try container.encodeIfPresent(version, forKey: .version)
    }
}


