//
// TaggedModuleDNS.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


public struct TaggedModuleDNS: Codable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case dns = "DNS"
    }
    public var type: ModelType
    public var value: DNSModule

    public init(type: ModelType, value: DNSModule) {
        self.type = type
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(value, forKey: .value)
    }
}


