//
// TaggedModuleCustom.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct TaggedModuleCustom: Codable, Hashable, Sendable {

    public enum ModelType: String, Codable, CaseIterable, Sendable {
        case custom = "Custom"
    }
    public var type: ModelType
    public var value: CustomModule

    public init(type: ModelType, value: CustomModule) {
        self.type = type
        self.value = value
    }
}

