//
// TaggedModuleOpenVPN.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


public struct TaggedModuleOpenVPN: Codable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case openVPN = "OpenVPN"
    }
    public var type: ModelType
    public var value: OpenVPNModule

    public init(type: ModelType, value: OpenVPNModule) {
        self.type = type
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(value, forKey: .value)
    }
}


