//
// TaggedModuleHTTPProxy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct TaggedModuleHTTPProxy: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case httpproxy = "HTTPProxy"
    }
    public let type: ModelType
    public let value: HTTPProxyModule

    public init(type: ModelType, value: HTTPProxyModule) {
        self.type = type
        self.value = value
    }
}

