//
// TaggedModuleHTTPProxy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


public struct TaggedModuleHTTPProxy: Codable, Hashable, Sendable {

    public enum ModelType: String, Codable, CaseIterable, Sendable {
        case httpproxy = "HTTPProxy"
    }

    public var type: ModelType
    public var value: HTTPProxyModule

    public init(type: ModelType, value: HTTPProxyModule) {
        self.type = type
        self.value = value
    }

}


