//
// TaggedProfile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


/** A codable wrapper for a profile with all known modules. */
public struct TaggedProfile: Codable, Hashable, Sendable {

    public var activeModulesIds: Set<UniqueID>
    public var behavior: ProfileBehavior?
    public var id: UniqueID
    public var modules: [TaggedModule]
    public var name: String
    public var userInfo: JSON?
    public var version: Int?

    public init(activeModulesIds: Set<UniqueID>, behavior: ProfileBehavior? = nil, id: UniqueID, modules: [TaggedModule], name: String, userInfo: JSON? = nil, version: Int? = nil) {
        self.activeModulesIds = activeModulesIds
        self.behavior = behavior
        self.id = id
        self.modules = modules
        self.name = name
        self.userInfo = userInfo
        self.version = version
    }

}


