//
// TaggedModuleOpenVPN.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct TaggedModuleOpenVPN: Codable, Hashable, Sendable {

    public enum ModelType: String, Codable, CaseIterable, Sendable {
        case openVPN = "OpenVPN"
    }
    public var type: ModelType
    public var value: OpenVPNModule

    public init(type: ModelType, value: OpenVPNModule) {
        self.type = type
        self.value = value
    }
}

