//
// TaggedModuleOpenVPN.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct TaggedModuleOpenVPN: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case openVPN = "OpenVPN"
    }
    public let type: ModelType
    public let value: OpenVPNModule

    public init(type: ModelType, value: OpenVPNModule) {
        self.type = type
        self.value = value
    }
}

