//
// TaggedModuleDNS.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


public struct TaggedModuleDNS: Codable, Hashable, Sendable {

    public enum ModelType: String, Codable, CaseIterable, Sendable {
        case dns = "DNS"
    }

    public var type: ModelType
    public var value: DNSModule

    public init(type: ModelType, value: DNSModule) {
        self.type = type
        self.value = value
    }

}


