//
// TaggedModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** A codable wrapper for all known modules. */
public enum TaggedModule: Codable, Hashable, Sendable {
    case Custom(CustomModule)
    case DNS(DNSModule)
    case HTTPProxy(HTTPProxyModule)
    case IP(IPModule)
    case OnDemand(OnDemandModule)
    case OpenVPN(OpenVPNModule)
    case WireGuard(WireGuardModule)

    private enum CodingKeys: String, CodingKey {
        case discriminator = "type"
        case value
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let rawType = try container.decode(String.self, forKey: .discriminator)
        let value = try container.superDecoder(forKey: .value)
        switch rawType {
        case "Custom":
            self = .Custom(try CustomModule(from: value))
        case "DNS":
            self = .DNS(try DNSModule(from: value))
        case "HTTPProxy":
            self = .HTTPProxy(try HTTPProxyModule(from: value))
        case "IP":
            self = .IP(try IPModule(from: value))
        case "OnDemand":
            self = .OnDemand(try OnDemandModule(from: value))
        case "OpenVPN":
            self = .OpenVPN(try OpenVPNModule(from: value))
        case "WireGuard":
            self = .WireGuard(try WireGuardModule(from: value))
        default:
            throw DecodingError.dataCorrupted(
                .init(codingPath: decoder.codingPath, debugDescription: "Unknown discriminator '\(rawType)'")
            )
        }
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {
        case .Custom(let value):
            try container.encode("Custom", forKey: .discriminator)
            try container.encode(value, forKey: .value)
        case .DNS(let value):
            try container.encode("DNS", forKey: .discriminator)
            try container.encode(value, forKey: .value)
        case .HTTPProxy(let value):
            try container.encode("HTTPProxy", forKey: .discriminator)
            try container.encode(value, forKey: .value)
        case .IP(let value):
            try container.encode("IP", forKey: .discriminator)
            try container.encode(value, forKey: .value)
        case .OnDemand(let value):
            try container.encode("OnDemand", forKey: .discriminator)
            try container.encode(value, forKey: .value)
        case .OpenVPN(let value):
            try container.encode("OpenVPN", forKey: .discriminator)
            try container.encode(value, forKey: .value)
        case .WireGuard(let value):
            try container.encode("WireGuard", forKey: .discriminator)
            try container.encode(value, forKey: .value)
        }
    }
}

