//
// TunnelSnapshot.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** Returns a tunnel-specific snapshot of a ``Profile``. */
public struct TunnelSnapshot: Sendable, Codable, Hashable {

    public let environment: TunnelSnapshotEnvironment?
    public let id: UniqueID
    public let isEnabled: Bool
    public let onDemand: Bool
    public let status: TunnelStatus

    public init(environment: TunnelSnapshotEnvironment? = nil, id: UniqueID, isEnabled: Bool, onDemand: Bool, status: TunnelStatus) {
        self.environment = environment
        self.id = id
        self.isEnabled = isEnabled
        self.onDemand = onDemand
        self.status = status
    }
}

