//
// TunnelSnapshot.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


/** Returns a tunnel-specific snapshot of a ``Profile``. */
public struct TunnelSnapshot: Codable, Hashable {

    public var environment: TunnelSnapshotEnvironment?
    public var id: UniqueID
    public var isEnabled: Bool
    public var onDemand: Bool
    public var status: TunnelStatus

    public init(environment: TunnelSnapshotEnvironment? = nil, id: UniqueID, isEnabled: Bool, onDemand: Bool, status: TunnelStatus) {
        self.environment = environment
        self.id = id
        self.isEnabled = isEnabled
        self.onDemand = onDemand
        self.status = status
    }

}


