//
// TunnelSnapshot.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** Returns a tunnel-specific snapshot of a ``Profile``. */
public struct TunnelSnapshot: Sendable, Codable, Hashable {

    public let id: UniqueID
    public let isEnabled: Bool
    public let status: TunnelStatus
    public let onDemand: Bool
    public let environment: TunnelSnapshotEnvironment?

    public init(id: UniqueID, isEnabled: Bool, status: TunnelStatus, onDemand: Bool, environment: TunnelSnapshotEnvironment? = nil) {
        self.id = id
        self.isEnabled = isEnabled
        self.status = status
        self.onDemand = onDemand
        self.environment = environment
    }
}

