//
// TunnelRemoteInfoWrapper.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct TunnelRemoteInfoWrapper: Sendable, Codable, Hashable {

    public let profile: TaggedProfile
    public let options: TunnelControllerOptions
    public let originalModuleId: UniqueID
    public let address: Address?
    public let requiresVirtualDevice: Bool
    public let modules: [TaggedModule]?

    public init(profile: TaggedProfile, options: TunnelControllerOptions, originalModuleId: UniqueID, address: Address? = nil, requiresVirtualDevice: Bool, modules: [TaggedModule]? = nil) {
        self.profile = profile
        self.options = options
        self.originalModuleId = originalModuleId
        self.address = address
        self.requiresVirtualDevice = requiresVirtualDevice
        self.modules = modules
    }
}

