//
// TunnelRemoteInfoWrapper.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct TunnelRemoteInfoWrapper: Sendable, Codable, Hashable {

    public let address: Address?
    public let modules: [TaggedModule]?
    public let options: TunnelControllerOptions
    public let originalModuleId: UniqueID
    public let profile: TaggedProfile
    public let requiresVirtualDevice: Bool

    public init(address: Address? = nil, modules: [TaggedModule]? = nil, options: TunnelControllerOptions, originalModuleId: UniqueID, profile: TaggedProfile, requiresVirtualDevice: Bool) {
        self.address = address
        self.modules = modules
        self.options = options
        self.originalModuleId = originalModuleId
        self.profile = profile
        self.requiresVirtualDevice = requiresVirtualDevice
    }
}

