//
// TunnelControllerOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** Common options to give to ``TunnelController``. */
public struct TunnelControllerOptions: Sendable, Codable, Hashable {

    public let dnsFallbackServers: [String]
    public let logsSnapshots: Bool
    public let minDataCountDelta: ModelUInt64

    public init(dnsFallbackServers: [String], logsSnapshots: Bool, minDataCountDelta: ModelUInt64) {
        self.dnsFallbackServers = dnsFallbackServers
        self.logsSnapshots = logsSnapshots
        self.minDataCountDelta = minDataCountDelta
    }
}

