//
// WireGuardRemoteInterface.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


/** The parameters of the remote interface. */
public struct WireGuardRemoteInterface: Codable, Hashable, Sendable {

    /** The list of allowed subnets. */
    public var allowedIPs: [Subnet]
    /** The optional endpoint. */
    public var endpoint: Endpoint?
    /** The keep-alive interval in seconds. */
    public var keepAlive: ModelUInt16?
    /** The optional endpoint pre-shared key. */
    public var preSharedKey: WireGuardKey?
    /** The endpoint public key. */
    public var publicKey: WireGuardKey

    public init(allowedIPs: [Subnet], endpoint: Endpoint? = nil, keepAlive: ModelUInt16? = nil, preSharedKey: WireGuardKey? = nil, publicKey: WireGuardKey) {
        self.allowedIPs = allowedIPs
        self.endpoint = endpoint
        self.keepAlive = keepAlive
        self.preSharedKey = preSharedKey
        self.publicKey = publicKey
    }

}


