//
// WireGuardModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** A connection module providing a WireGuard connection. */
public struct WireGuardModule: Sendable, Codable, Hashable {

    public let id: UniqueID
    public let configuration: WireGuardConfiguration?

    public init(id: UniqueID, configuration: WireGuardConfiguration? = nil) {
        self.id = id
        self.configuration = configuration
    }
}

