//
// WireGuardLocalInterface.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** The parameters of the local interface. */
public struct WireGuardLocalInterface: Sendable, Codable, Hashable {

    /** The local private key. */
    public var privateKey: WireGuardKey
    /** The local addresses. */
    public var addresses: [Subnet]
    /** The optional DNS settings. */
    public var dns: DNSModule?
    /** The optional MTU. */
    public var mtu: ModelUInt16?

    public init(privateKey: WireGuardKey, addresses: [Subnet], dns: DNSModule? = nil, mtu: ModelUInt16? = nil) {
        self.privateKey = privateKey
        self.addresses = addresses
        self.dns = dns
        self.mtu = mtu
    }
}

