//
// WireGuardLocalInterface.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

/** The parameters of the local interface. */
public struct WireGuardLocalInterface: Sendable, Codable, Hashable {

    /** The local addresses. */
    public let addresses: [Subnet]
    /** The optional DNS settings. */
    public let dns: DNSModule?
    /** The optional MTU. */
    public let mtu: ModelUInt16?
    /** The local private key. */
    public let privateKey: WireGuardKey

    public init(addresses: [Subnet], dns: DNSModule? = nil, mtu: ModelUInt16? = nil, privateKey: WireGuardKey) {
        self.addresses = addresses
        self.dns = dns
        self.mtu = mtu
        self.privateKey = privateKey
    }
}

