//
// WireGuardModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


/** A connection module providing a WireGuard connection. */
public struct WireGuardModule: Codable, Hashable {

    public var configuration: WireGuardConfiguration?
    public var id: UniqueID

    public init(configuration: WireGuardConfiguration? = nil, id: UniqueID) {
        self.configuration = configuration
        self.id = id
    }

}


