set(PARTOUT_MBEDTLS_DEPENDENCY "")

if(PP_USE_SYSTEM_VENDORS)
    partout_use_homebrew_formula(mbedtls)
    find_path(PARTOUT_MBEDTLS_INCLUDE_DIR mbedtls/ssl.h REQUIRED)
    find_library(PARTOUT_MBEDTLS_TLS_LIBRARY mbedtls REQUIRED)
    find_library(PARTOUT_MBEDTLS_X509_LIBRARY mbedx509 REQUIRED)
    find_library(PARTOUT_MBEDTLS_CRYPTO_LIBRARY mbedcrypto REQUIRED)
    get_filename_component(PARTOUT_MBEDTLS_LIBRARY_DIR
        "${PARTOUT_MBEDTLS_TLS_LIBRARY}" DIRECTORY)
    foreach(library IN ITEMS PARTOUT_MBEDTLS_X509_LIBRARY PARTOUT_MBEDTLS_CRYPTO_LIBRARY)
        get_filename_component(library_dir "${${library}}" DIRECTORY)
        if(NOT library_dir STREQUAL PARTOUT_MBEDTLS_LIBRARY_DIR)
            message(FATAL_ERROR "System Mbed TLS libraries must be in the same directory")
        endif()
    endforeach()
    message(STATUS "Using system Mbed TLS")
else()
    partout_use_prebuilt_vendor(mbedtls MBEDTLS_DIR)
    set(PARTOUT_MBEDTLS_INCLUDE_DIR "${MBEDTLS_DIR}/include")
    set(PARTOUT_MBEDTLS_LIBRARY_DIR "${MBEDTLS_DIR}/lib")
endif()
