set(PARTOUT_WGGO_DEPENDENCY "")

if(PP_SYSTEM_VENDORS_AVAILABLE)
    find_path(PARTOUT_WGGO_INCLUDE_DIR wg_go/wg_go.h)
    find_library(PARTOUT_WGGO_LIBRARY wg-go)
endif()

if(PP_SYSTEM_VENDORS_AVAILABLE AND PARTOUT_WGGO_INCLUDE_DIR AND PARTOUT_WGGO_LIBRARY)
    get_filename_component(PARTOUT_WGGO_LIBRARY_DIR "${PARTOUT_WGGO_LIBRARY}" DIRECTORY)
    set(WGGO_RUNTIME_LIBRARY "${PARTOUT_WGGO_LIBRARY}")
    message(STATUS "Using system wg-go")
else()
    partout_use_prebuilt_vendor(wg-go WGGO_DIR)
    set(PARTOUT_WGGO_INCLUDE_DIR "${WGGO_DIR}/include")
    set(PARTOUT_WGGO_LIBRARY_DIR "${WGGO_DIR}/lib")
    if(WIN32)
        set(WGGO_RUNTIME_LIBRARY "${WGGO_DIR}/lib/wg-go.dll")
    elseif(APPLE)
        set(WGGO_RUNTIME_LIBRARY "${WGGO_DIR}/lib/libwg-go.a")
    else()
        set(WGGO_RUNTIME_LIBRARY "${WGGO_DIR}/lib/libwg-go.so")
    endif()
endif()
