//
// DNSModuleDomainPolicy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public enum DNSModuleDomainPolicy: String, Codable, CaseIterable, Sendable {
    case match = "match"
    case matchAndSearch = "matchAndSearch"
}
