//
// TaggedModuleWireGuard.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

public struct TaggedModuleWireGuard: Codable, Hashable, Sendable {

    public enum ModelType: String, Codable, CaseIterable, Sendable {
        case wireGuard = "WireGuard"
    }
    public var type: ModelType
    public var value: WireGuardModule

    public init(type: ModelType, value: WireGuardModule) {
        self.type = type
        self.value = value
    }
}

