#!/bin/bash
set -e

usage() {
    echo "Usage: $0 <openapi> <language:kotlin|swift|cpp> <models_dir> <package_name> [extra_imports]"
    exit 1
}

if [ "$#" -lt 4 ]; then
    usage
fi

script_dir=$(cd "$(dirname "$0")" && pwd)
infile=$1
language=$2
models_dir=$3
package_name=$4
extra_imports=$5

postprocess_swift_tagged_module() {
    local openapi_file=$1
    local output_file=$2

    ruby -ryaml - "$openapi_file" "$output_file" <<'RUBY'
schemas = YAML.load_file(ARGV[0]).fetch("components").fetch("schemas")
tagged_module = schemas.fetch("TaggedModule")
property_name = tagged_module.fetch("discriminator").fetch("propertyName")
mapping = tagged_module.fetch("discriminator").fetch("mapping")
description = tagged_module["description"]

cases = mapping.map do |case_name, schema_ref|
  schema_name = schema_ref.delete_prefix("#/components/schemas/")
  value_ref = schemas.fetch(schema_name).fetch("properties").fetch("value").fetch("$ref")
  value_type = value_ref.delete_prefix("#/components/schemas/").delete(".")
  [case_name, value_type]
end

File.open(ARGV[1], "w") do |file|
  file.puts <<~SWIFT
    //
    // TaggedModule.swift
    //
    // Generated by openapi-generator
    // https://openapi-generator.tech
    //

  SWIFT
  file.puts "/** #{description} */" if description
  file.puts "public enum TaggedModule: Codable, Hashable, Sendable {"
  cases.each do |case_name, value_type|
    file.puts "    case #{case_name}(#{value_type})"
  end
  file.puts
  file.puts "    private enum CodingKeys: String, CodingKey {"
  file.puts "        case discriminator = \"#{property_name}\""
  file.puts "        case value"
  file.puts "    }"
  file.puts
  file.puts "    public init(from decoder: any Decoder) throws {"
  file.puts "        let container = try decoder.container(keyedBy: CodingKeys.self)"
  file.puts "        let rawType = try container.decode(String.self, forKey: .discriminator)"
  file.puts "        let value = try container.superDecoder(forKey: .value)"
  file.puts "        switch rawType {"
  cases.each do |case_name, value_type|
    file.puts "        case \"#{case_name}\":"
    file.puts "            self = .#{case_name}(try #{value_type}(from: value))"
  end
  file.puts "        default:"
  file.puts "            throw DecodingError.dataCorrupted("
  file.puts "                .init(codingPath: decoder.codingPath, debugDescription: \"Unknown discriminator '\\(rawType)'\")"
  file.puts "            )"
  file.puts "        }"
  file.puts "    }"
  file.puts
  file.puts "    public func encode(to encoder: any Encoder) throws {"
  file.puts "        var container = encoder.container(keyedBy: CodingKeys.self)"
  file.puts "        switch self {"
  cases.each do |case_name, _value_type|
    file.puts "        case .#{case_name}(let value):"
    file.puts "            try container.encode(\"#{case_name}\", forKey: .discriminator)"
    file.puts "            try container.encode(value, forKey: .value)"
  end
  file.puts "        }"
  file.puts "    }"
  file.puts "}"
  file.puts
end
RUBY
}

postprocess_swift_models() {
    local openapi_file=$1
    local models_dir=$2

    perl -0pi -e 's/&#x60;/`/g; s/&quot;/"/g; s/&gt;/>/g; s/&lt;/</g; s/&amp;/&/g' "$models_dir"/*.swift
    perl -0pi -e 's/^import Foundation\n//mg; s/^#if canImport\(AnyCodable\)\nimport AnyCodable\n#endif\n\n?//mg' "$models_dir"/*.swift
    perl -0pi -e 's/\n    public enum CodingKeys: String, CodingKey, CaseIterable(?:, Sendable)? \{\n(?:        case [^\n]+\n)*    \}\n//g; s/\n    \/\/ Encodable protocol methods\n\n    public func encode\(to encoder: Encoder\) throws \{\n(?:        .*\n)*?    \}\n//g' "$models_dir"/*.swift
    perl -0pi -e 's/^(\s*public (?:struct|final class|class|enum) [^{\n]+: (?![^{\n]*\bSendable\b)[^{\n]*?)\s*\{/$1, Sendable {/mg' "$models_dir"/*.swift
    postprocess_swift_tagged_module "$openapi_file" "$models_dir/TaggedModule.swift"
}

case $language in
    kotlin)
        kotlin_extra_imports_opts=()
        if [[ -n "$extra_imports" ]]; then
            IFS=',' read -ra extra_import_names <<< "$extra_imports"
            for name in "${extra_import_names[@]}"; do
                name="${name#"${name%%[![:space:]]*}"}"
                name="${name%"${name##*[![:space:]]}"}"

                if [[ -n "$name" ]]; then
                    kotlin_extra_imports_opts+=(
                        --import-mappings "$name=io.partout.models.$name"
                        --schema-mappings "$name=$name"
                    )
                fi
            done
        fi

        package_dir=${package_name//./\/}
        rm -rf $models_dir/src/main/kotlin/$package_dir
        openapi-generator generate \
            -i $infile \
            -o $models_dir \
            -g kotlin \
            --global-property=models,modelDocs=false,modelTests=false \
            --type-mappings number=Double,URI=String,kotlin.Any=kotlinx.serialization.json.JsonElement \
            --import-mappings Double=kotlin.Double,String=kotlin.String \
            --additional-properties=serializationLibrary=kotlinx_serialization \
            --additional-properties=packageName=$package_name \
            --additional-properties=modelPackage=$package_name \
            --schema-mappings OpenVPN.CryptoContainer=kotlin.String \
            "${kotlin_extra_imports_opts[@]}"
        ;;
    swift)
        # Generate into a temporary client package, then keep only the models.
        #
        # DocC comments are emitted by openapi-generator from OpenAPI schema
        # descriptions. Keep descriptions in openapi.yaml to preserve them here.
        tmp_dir="$(mktemp -d)"
        cleanup() {
            rm -rf "$tmp_dir"
        }
        trap cleanup EXIT

        project_name=$package_name
        rm -rf "$models_dir"
        openapi-generator generate \
            -i "$infile" \
            -o "$tmp_dir" \
            -g swift5 \
            --global-property=models,modelDocs=false,modelTests=false \
            --schema-mappings Address=Address \
            --schema-mappings DNSModule.ProtocolType=DNSModuleProtocolType \
            --schema-mappings Endpoint=Endpoint \
            --schema-mappings EndpointProtocol=EndpointProtocol \
            --schema-mappings ExtendedEndpoint=ExtendedEndpoint \
            --schema-mappings Subnet=Subnet \
            --schema-mappings UniqueID=UniqueID \
            --schema-mappings UInt16=UInt16 \
            --schema-mappings UInt32=UInt32 \
            --schema-mappings UInt64=UInt64 \
            --schema-mappings SecureData=SecureData \
            --schema-mappings OpenVPN.CryptoContainer=OpenVPNCryptoContainer \
            --schema-mappings OpenVPN.ObfuscationMethod=OpenVPNObfuscationMethod \
            --schema-mappings WireGuard.Key=WireGuardKey \
            --type-mappings AnyCodable=JSON,URI=URL \
            --additional-properties=projectName="$project_name" \
            --additional-properties=responseAs=AsyncAwait \
            --additional-properties=useSPMFileStructure=true \
            --additional-properties=useJsonEncodable=false \
            --additional-properties=useSendable=true \
            --additional-properties=validatable=false \
            --additional-properties=identifiableModels=false \
            --additional-properties=hashableModels=true

        generated_models_dir="$tmp_dir/Sources/$project_name/Models"
        mkdir -p "$models_dir"
        cp "$generated_models_dir"/*.swift "$models_dir"/
        postprocess_swift_models "$infile" "$models_dir"
        ;;
    cpp)
        echo "cpp language is not implemented yet; exiting."
        exit 0
        ;;
    *)
        echo "unknown language '$language'; expected 'kotlin', 'swift', or 'cpp'"
        exit 1
        ;;
esac
