//
// ABIErrorPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


public struct ABIErrorPayload: Codable, Hashable {

    public var code: PartoutErrorCode
    public var userInfo: JSON?

    public init(code: PartoutErrorCode, userInfo: JSON? = nil) {
        self.code = code
        self.userInfo = userInfo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case userInfo
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encodeIfPresent(userInfo, forKey: .userInfo)
    }
}


