//
// CustomModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


/** A type-erased ``Module`` for encoding external implementations. */
public struct CustomModule: Codable, Hashable {

    public var innerType: ModuleType
    public var json: JSON?

    public init(innerType: ModuleType, json: JSON?) {
        self.innerType = innerType
        self.json = json
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case innerType
        case json
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(innerType, forKey: .innerType)
        try container.encode(json, forKey: .json)
    }
}


