//
// CustomModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CustomModule: Codable, Hashable {

    public var innerType: ModuleType
    public var json: AnyCodable?

    public init(innerType: ModuleType, json: AnyCodable?) {
        self.innerType = innerType
        self.json = json
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case innerType
        case json
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(innerType, forKey: .innerType)
        try container.encode(json, forKey: .json)
    }
}

