//
// DataCount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A pair of received/sent bytes count. */
public struct DataCount: Codable, Hashable {

    /** Received bytes count. */
    public var received: Int64
    /** Sent bytes count. */
    public var sent: Int64

    public init(received: Int64, sent: Int64) {
        self.received = received
        self.sent = sent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case received
        case sent
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(received, forKey: .received)
        try container.encode(sent, forKey: .sent)
    }
}

