//
// DNSModuleDomainPolicy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum DNSModuleDomainPolicy: String, Codable, CaseIterable {
    case match = "match"
    case matchAndSearch = "matchAndSearch"
}
