//
// DNSModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DNSModule: Codable, Hashable {

    public var domainName: String?
    public var domainPolicy: DNSModuleDomainPolicy?
    public var id: String
    public var inheritsVPN: Bool?
    public var protocolType: DNSModuleProtocolType
    public var routesThroughVPN: Bool?
    public var searchDomains: [String]?
    public var servers: [String]

    public init(domainName: String? = nil, domainPolicy: DNSModuleDomainPolicy? = nil, id: String, inheritsVPN: Bool? = nil, protocolType: DNSModuleProtocolType, routesThroughVPN: Bool? = nil, searchDomains: [String]? = nil, servers: [String]) {
        self.domainName = domainName
        self.domainPolicy = domainPolicy
        self.id = id
        self.inheritsVPN = inheritsVPN
        self.protocolType = protocolType
        self.routesThroughVPN = routesThroughVPN
        self.searchDomains = searchDomains
        self.servers = servers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case domainName
        case domainPolicy
        case id
        case inheritsVPN
        case protocolType
        case routesThroughVPN
        case searchDomains
        case servers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(domainName, forKey: .domainName)
        try container.encodeIfPresent(domainPolicy, forKey: .domainPolicy)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(inheritsVPN, forKey: .inheritsVPN)
        try container.encode(protocolType, forKey: .protocolType)
        try container.encodeIfPresent(routesThroughVPN, forKey: .routesThroughVPN)
        try container.encodeIfPresent(searchDomains, forKey: .searchDomains)
        try container.encode(servers, forKey: .servers)
    }
}

