//
// DNSModuleProtocolTypeHttps.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DNSModuleProtocolTypeHttps: Codable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case https = "https"
    }
    public var type: ModelType
    public var url: String

    public init(type: ModelType, url: String) {
        self.type = type
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(url, forKey: .url)
    }
}

