//
// HTTPProxyModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct HTTPProxyModule: Codable, Hashable {

    public var bypassDomains: [String]
    public var id: String
    public var pacURL: String?
    public var proxy: String?
    public var secureProxy: String?

    public init(bypassDomains: [String], id: String, pacURL: String? = nil, proxy: String? = nil, secureProxy: String? = nil) {
        self.bypassDomains = bypassDomains
        self.id = id
        self.pacURL = pacURL
        self.proxy = proxy
        self.secureProxy = secureProxy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bypassDomains
        case id
        case pacURL
        case proxy
        case secureProxy
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(bypassDomains, forKey: .bypassDomains)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(pacURL, forKey: .pacURL)
        try container.encodeIfPresent(proxy, forKey: .proxy)
        try container.encodeIfPresent(secureProxy, forKey: .secureProxy)
    }
}

