//
// IPModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


/** IP and routes. */
public struct IPModule: Codable, Hashable {

    public var id: String
    public var ipv4: IPSettings?
    public var ipv6: IPSettings?
    public var mtu: Int?

    public init(id: String, ipv4: IPSettings? = nil, ipv6: IPSettings? = nil, mtu: Int? = nil) {
        self.id = id
        self.ipv4 = ipv4
        self.ipv6 = ipv6
        self.mtu = mtu
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case ipv4
        case ipv6
        case mtu
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(ipv4, forKey: .ipv4)
        try container.encodeIfPresent(ipv6, forKey: .ipv6)
        try container.encodeIfPresent(mtu, forKey: .mtu)
    }
}


