//
// IPSocketType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum IPSocketType: String, Codable, CaseIterable {
    case udp = "UDP"
    case tcp = "TCP"
    case udp4 = "UDP4"
    case tcp4 = "TCP4"
    case udp6 = "UDP6"
    case tcp6 = "TCP6"
}
