//
// ModuleType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ModuleType: String, Codable, CaseIterable {
    case Custom = "Custom"
    case DNS = "DNS"
    case HTTPProxy = "HTTPProxy"
    case IP = "IP"
    case OnDemand = "OnDemand"
    case OpenVPN = "OpenVPN"
    case Provider = "Provider"
    case WireGuard = "WireGuard"
    case Undefined = "Undefined"
}
