//
// OnDemandModulePolicy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum OnDemandModulePolicy: String, Codable, CaseIterable {
    case any = "any"
    case including = "including"
    case excluding = "excluding"
}
