//
// OnDemandModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** On-demand settings. */
public struct OnDemandModule: Codable, Hashable {

    public var id: String
    public var policy: OnDemandModulePolicy
    public var withOtherNetworks: Set<OnDemandModuleOtherNetwork>
    public var withSSIDs: [String: Bool]

    public init(id: String, policy: OnDemandModulePolicy, withOtherNetworks: Set<OnDemandModuleOtherNetwork>, withSSIDs: [String: Bool]) {
        self.id = id
        self.policy = policy
        self.withOtherNetworks = withOtherNetworks
        self.withSSIDs = withSSIDs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case policy
        case withOtherNetworks
        case withSSIDs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(policy, forKey: .policy)
        try container.encode(withOtherNetworks, forKey: .withOtherNetworks)
        try container.encode(withSSIDs, forKey: .withSSIDs)
    }
}

