//
// OpenVPNConfiguration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OpenVPNConfiguration: Codable, Hashable {

    public var authToken: String?
    public var authUserPass: Bool?
    public var ca: OpenVPNCryptoContainer?
    public var checksEKU: Bool?
    public var checksSANHost: Bool?
    public var cipher: OpenVPNCipher?
    public var clientCertificate: OpenVPNCryptoContainer?
    public var clientKey: OpenVPNCryptoContainer?
    public var compressionAlgorithm: OpenVPNCompressionAlgorithm?
    public var compressionFraming: OpenVPNCompressionFraming?
    public var dataCiphers: [OpenVPNCipher]?
    public var digest: OpenVPNDigest?
    public var dnsDomain: String?
    public var dnsServers: [String]?
    public var httpProxy: String?
    public var httpsProxy: String?
    public var ipv4: IPSettings?
    public var ipv6: IPSettings?
    public var keepAliveInterval: Double?
    public var keepAliveTimeout: Double?
    public var mtu: Int?
    public var noPullMask: [OpenVPNPullMask]?
    public var peerId: Int?
    public var proxyAutoConfigurationURL: String?
    public var proxyBypassDomains: [String]?
    public var randomizeEndpoint: Bool?
    public var randomizeHostnames: Bool?
    public var remotes: [String]?
    public var renegotiatesAfter: Double?
    public var routeGateway4: String?
    public var routeGateway6: String?
    public var routes4: [Route]?
    public var routes6: [Route]?
    public var routingPolicies: [OpenVPNRoutingPolicy]?
    public var sanHost: String?
    public var searchDomains: [String]?
    public var staticChallenge: Bool?
    public var tlsSecurityLevel: Int?
    public var tlsWrap: OpenVPNTLSWrap?
    public var usesPIAPatches: Bool?
    public var xorMethod: OpenVPNObfuscationMethod?

    public init(authToken: String? = nil, authUserPass: Bool? = nil, ca: OpenVPNCryptoContainer? = nil, checksEKU: Bool? = nil, checksSANHost: Bool? = nil, cipher: OpenVPNCipher? = nil, clientCertificate: OpenVPNCryptoContainer? = nil, clientKey: OpenVPNCryptoContainer? = nil, compressionAlgorithm: OpenVPNCompressionAlgorithm? = nil, compressionFraming: OpenVPNCompressionFraming? = nil, dataCiphers: [OpenVPNCipher]? = nil, digest: OpenVPNDigest? = nil, dnsDomain: String? = nil, dnsServers: [String]? = nil, httpProxy: String? = nil, httpsProxy: String? = nil, ipv4: IPSettings? = nil, ipv6: IPSettings? = nil, keepAliveInterval: Double? = nil, keepAliveTimeout: Double? = nil, mtu: Int? = nil, noPullMask: [OpenVPNPullMask]? = nil, peerId: Int? = nil, proxyAutoConfigurationURL: String? = nil, proxyBypassDomains: [String]? = nil, randomizeEndpoint: Bool? = nil, randomizeHostnames: Bool? = nil, remotes: [String]? = nil, renegotiatesAfter: Double? = nil, routeGateway4: String? = nil, routeGateway6: String? = nil, routes4: [Route]? = nil, routes6: [Route]? = nil, routingPolicies: [OpenVPNRoutingPolicy]? = nil, sanHost: String? = nil, searchDomains: [String]? = nil, staticChallenge: Bool? = nil, tlsSecurityLevel: Int? = nil, tlsWrap: OpenVPNTLSWrap? = nil, usesPIAPatches: Bool? = nil, xorMethod: OpenVPNObfuscationMethod? = nil) {
        self.authToken = authToken
        self.authUserPass = authUserPass
        self.ca = ca
        self.checksEKU = checksEKU
        self.checksSANHost = checksSANHost
        self.cipher = cipher
        self.clientCertificate = clientCertificate
        self.clientKey = clientKey
        self.compressionAlgorithm = compressionAlgorithm
        self.compressionFraming = compressionFraming
        self.dataCiphers = dataCiphers
        self.digest = digest
        self.dnsDomain = dnsDomain
        self.dnsServers = dnsServers
        self.httpProxy = httpProxy
        self.httpsProxy = httpsProxy
        self.ipv4 = ipv4
        self.ipv6 = ipv6
        self.keepAliveInterval = keepAliveInterval
        self.keepAliveTimeout = keepAliveTimeout
        self.mtu = mtu
        self.noPullMask = noPullMask
        self.peerId = peerId
        self.proxyAutoConfigurationURL = proxyAutoConfigurationURL
        self.proxyBypassDomains = proxyBypassDomains
        self.randomizeEndpoint = randomizeEndpoint
        self.randomizeHostnames = randomizeHostnames
        self.remotes = remotes
        self.renegotiatesAfter = renegotiatesAfter
        self.routeGateway4 = routeGateway4
        self.routeGateway6 = routeGateway6
        self.routes4 = routes4
        self.routes6 = routes6
        self.routingPolicies = routingPolicies
        self.sanHost = sanHost
        self.searchDomains = searchDomains
        self.staticChallenge = staticChallenge
        self.tlsSecurityLevel = tlsSecurityLevel
        self.tlsWrap = tlsWrap
        self.usesPIAPatches = usesPIAPatches
        self.xorMethod = xorMethod
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case authToken
        case authUserPass
        case ca
        case checksEKU
        case checksSANHost
        case cipher
        case clientCertificate
        case clientKey
        case compressionAlgorithm
        case compressionFraming
        case dataCiphers
        case digest
        case dnsDomain
        case dnsServers
        case httpProxy
        case httpsProxy
        case ipv4
        case ipv6
        case keepAliveInterval
        case keepAliveTimeout
        case mtu
        case noPullMask
        case peerId
        case proxyAutoConfigurationURL
        case proxyBypassDomains
        case randomizeEndpoint
        case randomizeHostnames
        case remotes
        case renegotiatesAfter
        case routeGateway4
        case routeGateway6
        case routes4
        case routes6
        case routingPolicies
        case sanHost
        case searchDomains
        case staticChallenge
        case tlsSecurityLevel
        case tlsWrap
        case usesPIAPatches
        case xorMethod
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(authToken, forKey: .authToken)
        try container.encodeIfPresent(authUserPass, forKey: .authUserPass)
        try container.encodeIfPresent(ca, forKey: .ca)
        try container.encodeIfPresent(checksEKU, forKey: .checksEKU)
        try container.encodeIfPresent(checksSANHost, forKey: .checksSANHost)
        try container.encodeIfPresent(cipher, forKey: .cipher)
        try container.encodeIfPresent(clientCertificate, forKey: .clientCertificate)
        try container.encodeIfPresent(clientKey, forKey: .clientKey)
        try container.encodeIfPresent(compressionAlgorithm, forKey: .compressionAlgorithm)
        try container.encodeIfPresent(compressionFraming, forKey: .compressionFraming)
        try container.encodeIfPresent(dataCiphers, forKey: .dataCiphers)
        try container.encodeIfPresent(digest, forKey: .digest)
        try container.encodeIfPresent(dnsDomain, forKey: .dnsDomain)
        try container.encodeIfPresent(dnsServers, forKey: .dnsServers)
        try container.encodeIfPresent(httpProxy, forKey: .httpProxy)
        try container.encodeIfPresent(httpsProxy, forKey: .httpsProxy)
        try container.encodeIfPresent(ipv4, forKey: .ipv4)
        try container.encodeIfPresent(ipv6, forKey: .ipv6)
        try container.encodeIfPresent(keepAliveInterval, forKey: .keepAliveInterval)
        try container.encodeIfPresent(keepAliveTimeout, forKey: .keepAliveTimeout)
        try container.encodeIfPresent(mtu, forKey: .mtu)
        try container.encodeIfPresent(noPullMask, forKey: .noPullMask)
        try container.encodeIfPresent(peerId, forKey: .peerId)
        try container.encodeIfPresent(proxyAutoConfigurationURL, forKey: .proxyAutoConfigurationURL)
        try container.encodeIfPresent(proxyBypassDomains, forKey: .proxyBypassDomains)
        try container.encodeIfPresent(randomizeEndpoint, forKey: .randomizeEndpoint)
        try container.encodeIfPresent(randomizeHostnames, forKey: .randomizeHostnames)
        try container.encodeIfPresent(remotes, forKey: .remotes)
        try container.encodeIfPresent(renegotiatesAfter, forKey: .renegotiatesAfter)
        try container.encodeIfPresent(routeGateway4, forKey: .routeGateway4)
        try container.encodeIfPresent(routeGateway6, forKey: .routeGateway6)
        try container.encodeIfPresent(routes4, forKey: .routes4)
        try container.encodeIfPresent(routes6, forKey: .routes6)
        try container.encodeIfPresent(routingPolicies, forKey: .routingPolicies)
        try container.encodeIfPresent(sanHost, forKey: .sanHost)
        try container.encodeIfPresent(searchDomains, forKey: .searchDomains)
        try container.encodeIfPresent(staticChallenge, forKey: .staticChallenge)
        try container.encodeIfPresent(tlsSecurityLevel, forKey: .tlsSecurityLevel)
        try container.encodeIfPresent(tlsWrap, forKey: .tlsWrap)
        try container.encodeIfPresent(usesPIAPatches, forKey: .usesPIAPatches)
        try container.encodeIfPresent(xorMethod, forKey: .xorMethod)
    }
}

