//
// OpenVPNTLSWrap.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Holds parameters for TLS wrapping. */
public struct OpenVPNTLSWrap: Codable, Hashable {

    /** The static encryption key. */
    public var key: OpenVPNStaticKey
    /** The wrapping strategy. */
    public var strategy: OpenVPNTLSWrapStrategy
    /** The wrapped client key appended to initial tls-crypt-v2 packets. */
    public var wrappedKey: String?

    public init(key: OpenVPNStaticKey, strategy: OpenVPNTLSWrapStrategy, wrappedKey: String? = nil) {
        self.key = key
        self.strategy = strategy
        self.wrappedKey = wrappedKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
        case strategy
        case wrappedKey
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(key, forKey: .key)
        try container.encode(strategy, forKey: .strategy)
        try container.encodeIfPresent(wrappedKey, forKey: .wrappedKey)
    }
}

