//
// OpenVPNTLSWrapStrategy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum OpenVPNTLSWrapStrategy: String, Codable, CaseIterable {
    case auth = "auth"
    case crypt = "crypt"
    case cryptV2 = "crypt-v2"
}
