//
// OpenVPNStaticKeyDirection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum OpenVPNStaticKeyDirection: Int, Codable, CaseIterable {
    case server = 0
    case client = 1
}
