//
// OpenVPNRoutingPolicy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum OpenVPNRoutingPolicy: String, Codable, CaseIterable {
    case IPv4 = "IPv4"
    case IPv6 = "IPv6"
    case blockLocal = "blockLocal"
}
