//
// OpenVPNPullMask.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum OpenVPNPullMask: String, Codable, CaseIterable {
    case routes = "routes"
    case dns = "dns"
    case proxy = "proxy"
}
