//
// OpenVPNStaticKey.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


/** Represents an OpenVPN static key file (as generated with --genkey) */
public struct OpenVPNStaticKey: Codable, Hashable {

    /** Wrapper of a byte array with safe encoding capabilities. */
    public var data: String
    public var dir: OpenVPNStaticKeyDirection?

    public init(data: String, dir: OpenVPNStaticKeyDirection? = nil) {
        self.data = data
        self.dir = dir
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case dir
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encodeIfPresent(dir, forKey: .dir)
    }
}


