//
// OpenVPNCompressionAlgorithm.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum OpenVPNCompressionAlgorithm: Int, Codable, CaseIterable {
    case disabled = 0
    case LZO = 1
    case other = 2
}
