//
// OpenVPNCredentials.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A set of credentials for authentication. */
public struct OpenVPNCredentials: Codable, Hashable {

    /** The OTP. */
    public var otp: String?
    /** The OTP method (defaults to ``OTPMethod-swift.enum/none``). */
    public var otpMethod: OpenVPNCredentialsOTPMethod
    /** The password. */
    public var password: String
    /** The username. */
    public var username: String

    public init(otp: String? = nil, otpMethod: OpenVPNCredentialsOTPMethod, password: String, username: String) {
        self.otp = otp
        self.otpMethod = otpMethod
        self.password = password
        self.username = username
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case otp
        case otpMethod
        case password
        case username
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(otp, forKey: .otp)
        try container.encode(otpMethod, forKey: .otpMethod)
        try container.encode(password, forKey: .password)
        try container.encode(username, forKey: .username)
    }
}

