//
// OpenVPNObfuscationMethodXormask.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OpenVPNObfuscationMethodXormask: Codable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case xormask = "xormask"
    }
    public var type: ModelType
    public var mask: String

    public init(type: ModelType, mask: String) {
        self.type = type
        self.mask = mask
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case mask
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(mask, forKey: .mask)
    }
}

