//
// OpenVPNCredentialsOTPMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum OpenVPNCredentialsOTPMethod: String, Codable, CaseIterable {
    case none = "none"
    case append = "append"
    case encode = "encode"
}
