//
// OpenVPNDigest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum OpenVPNDigest: String, Codable, CaseIterable {
    case sha1 = "SHA1"
    case sha224 = "SHA224"
    case sha256 = "SHA256"
    case sha384 = "SHA384"
    case sha512 = "SHA512"
}
