//
// OpenVPNCipher.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum OpenVPNCipher: String, Codable, CaseIterable {
    case aes128cbc = "AES-128-CBC"
    case aes192cbc = "AES-192-CBC"
    case aes256cbc = "AES-256-CBC"
    case aes128gcm = "AES-128-GCM"
    case aes192gcm = "AES-192-GCM"
    case aes256gcm = "AES-256-GCM"
}
