//
// OpenVPNCryptoContainer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Represents a cryptographic container in PEM format. */
public struct OpenVPNCryptoContainer: Codable, Hashable {

    /** The content in PEM format (ASCII). */
    public var pem: String

    public init(pem: String) {
        self.pem = pem
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pem
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pem, forKey: .pem)
    }
}

