//
// OpenVPNModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A connection module providing an OpenVPN connection. */
public struct OpenVPNModule: Codable, Hashable {

    public var configuration: OpenVPNConfiguration?
    public var credentials: OpenVPNCredentials?
    public var id: String
    public var requiresInteractiveCredentials: Bool?

    public init(configuration: OpenVPNConfiguration? = nil, credentials: OpenVPNCredentials? = nil, id: String, requiresInteractiveCredentials: Bool? = nil) {
        self.configuration = configuration
        self.credentials = credentials
        self.id = id
        self.requiresInteractiveCredentials = requiresInteractiveCredentials
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case configuration
        case credentials
        case id
        case requiresInteractiveCredentials
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(configuration, forKey: .configuration)
        try container.encodeIfPresent(credentials, forKey: .credentials)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(requiresInteractiveCredentials, forKey: .requiresInteractiveCredentials)
    }
}

