//
// PartoutErrorCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum PartoutErrorCode: String, Codable, CaseIterable {
    case cached = "cached"
    case notFound = "notFound"
    case operationCancelled = "operationCancelled"
    case releasedObject = "releasedObject"
    case scriptException = "scriptException"
    case timeout = "timeout"
    case unhandled = "unhandled"
    case incompatibleModules = "incompatibleModules"
    case incompleteModule = "incompleteModule"
    case noActiveModules = "noActiveModules"
    case nonFinalModules = "nonFinalModules"
    case requiredImplementation = "requiredImplementation"
    case unexpectedModuleType = "unexpectedModuleType"
    case unknownImportedModule = "unknownImportedModule"
    case unknownModuleHandler = "unknownModuleHandler"
    case authentication = "authentication"
    case crypto = "crypto"
    case dnsFailure = "dnsFailure"
    case exhaustedEndpoints = "exhaustedEndpoints"
    case fdUnavailable = "fdUnavailable"
    case ioFailure = "ioFailure"
    case linkNotActive = "linkNotActive"
    case networkChanged = "networkChanged"
    case networkUnreachable = "networkUnreachable"
    case socketConfiguration = "socketConfiguration"
    case tunNotActive = "tunNotActive"
    case tunNotAvailable = "tunNotAvailable"
    case decoding = "decoding"
    case encoding = "encoding"
    case invalidField = "invalidField"
    case invalidValue = "invalidValue"
    case parsing = "parsing"
    case keychainAddItem = "keychainAddItem"
    case keychainItemNotFound = "keychainItemNotFound"
    case openVPNCompressionMismatch = "OpenVPN.compressionMismatch"
    case openVPNConnectionFailure = "OpenVPN.connectionFailure"
    case openVPNNoRouting = "OpenVPN.noRouting"
    case openVPNOTPRequired = "OpenVPN.otpRequired"
    case openVPNPassphraseRequired = "OpenVPN.passphraseRequired"
    case openVPNRecoverableAuthentication = "OpenVPN.recoverableAuthentication"
    case openVPNServerShutdown = "OpenVPN.serverShutdown"
    case openVPNTLSFailure = "OpenVPN.tlsFailure"
    case openVPNUnsupportedAlgorithm = "OpenVPN.unsupportedAlgorithm"
    case openVPNUnsupportedCompression = "OpenVPN.unsupportedCompression"
    case openVPNUnsupportedOption = "OpenVPN.unsupportedOption"
    case wireGuardEmptyPeers = "WireGuard.emptyPeers"
}
