//
// ProfileBehavior.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Advanced flags affecting the behavior of a ``Profile``. */
public struct ProfileBehavior: Codable, Hashable {

    /** Disconnects when the device goes to sleep. */
    public var disconnectsOnSleep: Bool
    /** Attempts to route as much traffic as possible through the tunnel. */
    public var includesAllNetworks: Bool?

    public init(disconnectsOnSleep: Bool, includesAllNetworks: Bool? = nil) {
        self.disconnectsOnSleep = disconnectsOnSleep
        self.includesAllNetworks = includesAllNetworks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case disconnectsOnSleep
        case includesAllNetworks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(disconnectsOnSleep, forKey: .disconnectsOnSleep)
        try container.encodeIfPresent(includesAllNetworks, forKey: .includesAllNetworks)
    }
}

