//
// Route.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Route: Codable, Hashable {

    public var destination: String?
    public var gateway: String?

    public init(destination: String? = nil, gateway: String? = nil) {
        self.destination = destination
        self.gateway = gateway
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case destination
        case gateway
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(destination, forKey: .destination)
        try container.encodeIfPresent(gateway, forKey: .gateway)
    }
}

