//
// SocketType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A socket type between UDP and TCP. */
public enum SocketType: String, Codable, CaseIterable {
    /// UDP socket type.
    case udp = "UDP"
    /// TCP socket type.
    case tcp = "TCP"
}
