//
// SocketType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum SocketType: String, Codable, CaseIterable {
    case udp = "UDP"
    case tcp = "TCP"
}
