//
// TaggedModuleIP.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TaggedModuleIP: Codable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case ip = "IP"
    }
    public var type: ModelType
    public var value: IPModule

    public init(type: ModelType, value: IPModule) {
        self.type = type
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(value, forKey: .value)
    }
}

