//
// TunnelSnapshotEnvironment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


public struct TunnelSnapshotEnvironment: Codable, Hashable {

    public var connectionStatus: ConnectionStatus
    public var dataCount: DataCount
    public var lastErrorCode: String?

    public init(connectionStatus: ConnectionStatus, dataCount: DataCount, lastErrorCode: String? = nil) {
        self.connectionStatus = connectionStatus
        self.dataCount = dataCount
        self.lastErrorCode = lastErrorCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case connectionStatus
        case dataCount
        case lastErrorCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(connectionStatus, forKey: .connectionStatus)
        try container.encode(dataCount, forKey: .dataCount)
        try container.encodeIfPresent(lastErrorCode, forKey: .lastErrorCode)
    }
}


