//
// TunnelStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The status of a ``Tunnel``. */
public enum TunnelStatus: String, Codable, CaseIterable {
    case inactive = "inactive"
    case activating = "activating"
    case active = "active"
    case deactivating = "deactivating"
}
