//
// TunnelSnapshot.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Returns a tunnel-specific snapshot of a ``Profile``. */
public struct TunnelSnapshot: Codable, Hashable {

    public var environment: TunnelSnapshotEnvironment?
    public var id: String
    public var isEnabled: Bool
    public var onDemand: Bool
    public var status: TunnelStatus

    public init(environment: TunnelSnapshotEnvironment? = nil, id: String, isEnabled: Bool, onDemand: Bool, status: TunnelStatus) {
        self.environment = environment
        self.id = id
        self.isEnabled = isEnabled
        self.onDemand = onDemand
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case environment
        case id
        case isEnabled
        case onDemand
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(environment, forKey: .environment)
        try container.encode(id, forKey: .id)
        try container.encode(isEnabled, forKey: .isEnabled)
        try container.encode(onDemand, forKey: .onDemand)
        try container.encode(status, forKey: .status)
    }
}

