//
// WireGuardRemoteInterface.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WireGuardRemoteInterface: Codable, Hashable {

    public var allowedIPs: [String]
    public var endpoint: String?
    public var keepAlive: Int?
    public var preSharedKey: String?
    public var publicKey: String

    public init(allowedIPs: [String], endpoint: String? = nil, keepAlive: Int? = nil, preSharedKey: String? = nil, publicKey: String) {
        self.allowedIPs = allowedIPs
        self.endpoint = endpoint
        self.keepAlive = keepAlive
        self.preSharedKey = preSharedKey
        self.publicKey = publicKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case allowedIPs
        case endpoint
        case keepAlive
        case preSharedKey
        case publicKey
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(allowedIPs, forKey: .allowedIPs)
        try container.encodeIfPresent(endpoint, forKey: .endpoint)
        try container.encodeIfPresent(keepAlive, forKey: .keepAlive)
        try container.encodeIfPresent(preSharedKey, forKey: .preSharedKey)
        try container.encode(publicKey, forKey: .publicKey)
    }
}

