//
// WireGuardConfiguration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//


/** Represents a WireGuard configuration. */
public struct WireGuardConfiguration: Codable, Hashable {

    /** The local interface. */
    public var interface: WireGuardLocalInterface
    /** The peers. */
    public var peers: [WireGuardRemoteInterface]

    public init(interface: WireGuardLocalInterface, peers: [WireGuardRemoteInterface]) {
        self.interface = interface
        self.peers = peers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case interface
        case peers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(interface, forKey: .interface)
        try container.encode(peers, forKey: .peers)
    }
}


