//
// WireGuardModule.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A connection module providing a WireGuard connection. */
public struct WireGuardModule: Codable, Hashable {

    public var configuration: WireGuardConfiguration?
    public var id: String

    public init(configuration: WireGuardConfiguration? = nil, id: String) {
        self.configuration = configuration
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case configuration
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(configuration, forKey: .configuration)
        try container.encode(id, forKey: .id)
    }
}

