//
// WireGuardLocalInterface.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WireGuardLocalInterface: Codable, Hashable {

    public var addresses: [String]
    public var dns: DNSModule?
    public var mtu: Int?
    public var privateKey: String

    public init(addresses: [String], dns: DNSModule? = nil, mtu: Int? = nil, privateKey: String) {
        self.addresses = addresses
        self.dns = dns
        self.mtu = mtu
        self.privateKey = privateKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case addresses
        case dns
        case mtu
        case privateKey
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(addresses, forKey: .addresses)
        try container.encodeIfPresent(dns, forKey: .dns)
        try container.encodeIfPresent(mtu, forKey: .mtu)
        try container.encode(privateKey, forKey: .privateKey)
    }
}

