/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.partout.abi

import io.partout.abi.ConnectionStatus
import io.partout.abi.DataCount

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param connectionStatus 
 * @param dataCount 
 * @param lastErrorCode 
 */
@Serializable

data class TunnelSnapshotEnvironment (

    @Contextual @SerialName(value = "connectionStatus")
    val connectionStatus: ConnectionStatus,

    @SerialName(value = "dataCount")
    val dataCount: DataCount,

    @SerialName(value = "lastErrorCode")
    val lastErrorCode: kotlin.String? = null

) {


}

