include_guard(GLOBAL)
include(FetchContent)

function(partout_prebuilt_vendor_target output_target)
    if(WIN32 OR CMAKE_SYSTEM_NAME STREQUAL "Linux")
        if(DEFINED ARCH_NAME)
            set(system_processor "${ARCH_NAME}")
        elseif(CMAKE_C_COMPILER_ARCHITECTURE_ID)
            set(system_processor "${CMAKE_C_COMPILER_ARCHITECTURE_ID}")
        elseif(CMAKE_C_COMPILER_TARGET)
            set(system_processor "${CMAKE_C_COMPILER_TARGET}")
        elseif(DEFINED ENV{VSCMD_ARG_TGT_ARCH})
            set(system_processor "$ENV{VSCMD_ARG_TGT_ARCH}")
        else()
            set(system_processor "${CMAKE_SYSTEM_PROCESSOR}")
        endif()
        string(TOLOWER "${system_processor}" system_processor)
    endif()

    if(ANDROID)
        if(DEFINED ANDROID_ABI)
            set(android_abi "${ANDROID_ABI}")
        elseif(DEFINED CMAKE_ANDROID_ARCH_ABI)
            set(android_abi "${CMAKE_ANDROID_ARCH_ABI}")
        else()
            set(android_abi "")
        endif()
        if(NOT android_abi STREQUAL "arm64-v8a")
            message(FATAL_ERROR "Prebuilt vendors only support Android arm64-v8a")
        endif()
        set(target "android-arm64-v8a")
    elseif(APPLE)
        set(target "apple-xcframework")
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        if(system_processor MATCHES "^(arm64|aarch64)(-|$)")
            set(target "linux-arm64")
        elseif(system_processor MATCHES "^(amd64|x86_64|x64)(-|$)")
            set(target "linux-x64")
        else()
            message(FATAL_ERROR
                "Prebuilt vendors do not support Linux architecture '${system_processor}'")
        endif()
    elseif(WIN32)
        if(system_processor MATCHES "^(arm64|aarch64)(-|$)")
            set(target "windows-arm64")
        elseif(system_processor MATCHES "^(amd64|x86_64|x64)(-|$)")
            set(target "windows-x64")
        else()
            message(FATAL_ERROR "Prebuilt vendors do not support Windows architecture '${CMAKE_SYSTEM_PROCESSOR}'")
        endif()
    else()
        message(FATAL_ERROR "Prebuilt vendors only support Android, Apple, Linux, and Windows")
    endif()

    set(${output_target} "${target}" PARENT_SCOPE)
endfunction()

function(partout_prepare_apple_vendor source_dir vendor_dir vendor)
    if(EXISTS "${source_dir}/Info.plist")
        set(xcframework "${source_dir}")
    else()
        file(GLOB xcframeworks LIST_DIRECTORIES TRUE "${source_dir}/*.xcframework")
        list(LENGTH xcframeworks xcframework_count)
        if(NOT xcframework_count EQUAL 1)
            message(FATAL_ERROR "Expected one XCFramework in ${source_dir}")
        endif()
        list(GET xcframeworks 0 xcframework)
    endif()

    file(GLOB macos_slices LIST_DIRECTORIES TRUE "${xcframework}/macos-*")
    list(LENGTH macos_slices macos_slice_count)
    if(NOT macos_slice_count EQUAL 1)
        message(FATAL_ERROR "Expected one macOS slice in ${xcframework}")
    endif()
    list(GET macos_slices 0 macos_slice)

    file(MAKE_DIRECTORY "${vendor_dir}/include" "${vendor_dir}/lib")
    file(COPY "${macos_slice}/Headers/" DESTINATION "${vendor_dir}/include")
    if(vendor STREQUAL "openssl")
        set(source_library "${macos_slice}/libopenssl.a")
        set(libraries libssl.a libcrypto.a)
    elseif(vendor STREQUAL "mbedtls")
        set(source_library "${macos_slice}/libmbedtls.a")
        set(libraries libmbedtls.a libmbedx509.a libmbedcrypto.a)
    elseif(vendor STREQUAL "wg-go")
        set(source_library "${macos_slice}/libwg-go.a")
        set(libraries libwg-go.a)
    else()
        message(FATAL_ERROR "No Apple XCFramework mapping for ${vendor}")
    endif()
    foreach(library IN LISTS libraries)
        file(COPY_FILE "${source_library}" "${vendor_dir}/lib/${library}")
    endforeach()
endfunction()

function(partout_prebuilt_vendor_archive vendor target output_archive)
    if(target STREQUAL "apple-xcframework")
        set(archive "${vendor}.xcframework.zip")
    elseif(target MATCHES "^windows-")
        set(archive "${vendor}-${target}.zip")
    else()
        set(archive "${vendor}-${target}.tar.gz")
    endif()
    set(${output_archive} "${archive}" PARENT_SCOPE)
endfunction()

function(partout_use_prebuilt_vendor vendor output_dir)
    if(NOT vendor MATCHES "^(mbedtls|openssl|wg-go|wintun)$")
        message(FATAL_ERROR "No prebuilt archive configured for vendor '${vendor}'")
    endif()

    partout_prebuilt_vendor_target(target)
    if(NOT PP_BUILD_VENDOR_PREBUILT_URL)
        message(FATAL_ERROR
            "PP_BUILD_VENDOR_PREBUILT_URL is required for prebuilt vendor '${vendor}'")
    endif()
    partout_prebuilt_vendor_archive("${vendor}" "${target}" archive)
    string(REGEX REPLACE "/+$" "" vendor_root "${PP_BUILD_VENDOR_PREBUILT_URL}")
    string(REPLACE "-" "_" vendor_id "${vendor}")
    string(TOUPPER "${vendor_id}" vendor_id)
    set(hash_var "PP_BUILD_${vendor_id}_PREBUILT_HASH")
    string(REPLACE "-" "_" content_name "partout_${vendor}_${target}_prebuilt")

    set(fetch_content_args
        URL "${vendor_root}/${archive}"
        SOURCE_SUBDIR "__partout_no_cmake_subdir"
        DOWNLOAD_EXTRACT_TIMESTAMP FALSE
    )
    if(DEFINED ${hash_var} AND NOT "${${hash_var}}" STREQUAL "")
        list(APPEND fetch_content_args URL_HASH "${${hash_var}}")
    endif()

    FetchContent_Declare(${content_name} ${fetch_content_args})
    FetchContent_MakeAvailable(${content_name})
    FetchContent_GetProperties(${content_name} SOURCE_DIR source_dir)

    get_filename_component(output_root "${PP_BUILD_OUTPUT}" ABSOLUTE)
    set(vendor_dir "${output_root}/${vendor}")
    if(NOT "${source_dir}" STREQUAL "${vendor_dir}")
        file(REMOVE_RECURSE "${vendor_dir}")
        if(APPLE)
            partout_prepare_apple_vendor("${source_dir}" "${vendor_dir}" "${vendor}")
        else()
            file(MAKE_DIRECTORY "${vendor_dir}")
            file(COPY "${source_dir}/" DESTINATION "${vendor_dir}" USE_SOURCE_PERMISSIONS)
        endif()
    endif()

    set(${output_dir} "${vendor_dir}" PARENT_SCOPE)
    message(STATUS "Using prebuilt ${vendor} (${target})")
endfunction()
