include_guard(GLOBAL)
include(FetchContent)

function(partout_prebuilt_vendor_target output_target)
    if(ANDROID)
        if(DEFINED ANDROID_ABI)
            set(android_abi "${ANDROID_ABI}")
        elseif(DEFINED CMAKE_ANDROID_ARCH_ABI)
            set(android_abi "${CMAKE_ANDROID_ARCH_ABI}")
        else()
            set(android_abi "")
        endif()
        if(NOT android_abi STREQUAL "arm64-v8a")
            message(FATAL_ERROR "Prebuilt vendors only support Android arm64-v8a")
        endif()
        set(target "android-arm64-v8a")
    elseif(WIN32)
        if(DEFINED ARCH_NAME)
            set(system_processor "${ARCH_NAME}")
        elseif(CMAKE_C_COMPILER_ARCHITECTURE_ID)
            set(system_processor "${CMAKE_C_COMPILER_ARCHITECTURE_ID}")
        elseif(CMAKE_C_COMPILER_TARGET)
            set(system_processor "${CMAKE_C_COMPILER_TARGET}")
        elseif(DEFINED ENV{VSCMD_ARG_TGT_ARCH})
            set(system_processor "$ENV{VSCMD_ARG_TGT_ARCH}")
        else()
            set(system_processor "${CMAKE_SYSTEM_PROCESSOR}")
        endif()
        string(TOLOWER "${system_processor}" system_processor)
        if(system_processor MATCHES "^(arm64|aarch64)(-|$)")
            set(target "windows-arm64")
        elseif(system_processor MATCHES "^(amd64|x86_64|x64)(-|$)")
            set(target "windows-x64")
        else()
            message(FATAL_ERROR "Prebuilt vendors do not support Windows architecture '${CMAKE_SYSTEM_PROCESSOR}'")
        endif()
    else()
        message(FATAL_ERROR "Prebuilt vendors only support Android and Windows")
    endif()

    set(${output_target} "${target}" PARENT_SCOPE)
endfunction()

function(partout_prebuilt_vendor_archive target output_archive)
    if(target MATCHES "^windows-")
        set(archive "partout-vendors-${target}.zip")
    else()
        set(archive "partout-vendors-${target}.tar.gz")
    endif()

    set(${output_archive} "${archive}" PARENT_SCOPE)
endfunction()

function(partout_prepare_prebuilt_vendors)
    if(PP_BUILD_VENDOR_ROOT)
        get_filename_component(vendor_root "${PP_BUILD_VENDOR_ROOT}" ABSOLUTE)
        if(NOT IS_DIRECTORY "${vendor_root}")
            message(FATAL_ERROR "PP_BUILD_VENDOR_ROOT does not exist: ${vendor_root}")
        endif()
        set(PP_VENDOR_ROOT "${vendor_root}" PARENT_SCOPE)
        message(STATUS "Using local prebuilt vendors from ${vendor_root}")
        return()
    endif()

    if(NOT PP_BUILD_VENDOR_PREBUILT_URL)
        message(FATAL_ERROR
            "Set PP_BUILD_VENDOR_ROOT or PP_BUILD_VENDOR_PREBUILT_URL when using prebuilt vendors")
    endif()

    partout_prebuilt_vendor_target(target)
    partout_prebuilt_vendor_archive("${target}" archive)
    string(REGEX REPLACE "/+$" "" vendor_url "${PP_BUILD_VENDOR_PREBUILT_URL}")
    string(REPLACE "-" "_" target_id "${target}")
    set(content_name "ppv_${target_id}")
    string(REPLACE "-" "_" verification_name "${target}")
    string(TOUPPER "${verification_name}" verification_name)
    set(verification_var "PP_BUILD_VENDOR_PREBUILT_VERIFICATION_${verification_name}")

    set(fetch_content_args
        URL "${vendor_url}/${archive}"
        SOURCE_SUBDIR "__partout_no_cmake_subdir"
        DOWNLOAD_EXTRACT_TIMESTAMP FALSE
    )
    if(DEFINED ${verification_var} AND NOT "${${verification_var}}" STREQUAL "")
        list(APPEND fetch_content_args URL_HASH "${${verification_var}}")
    endif()

    FetchContent_Declare(${content_name} ${fetch_content_args})
    FetchContent_MakeAvailable(${content_name})
    FetchContent_GetProperties(${content_name} SOURCE_DIR source_dir)

    set(PP_VENDOR_ROOT "${source_dir}" PARENT_SCOPE)
    message(STATUS "Using prebuilt vendors (${target})")
endfunction()

function(partout_use_prebuilt_vendor vendor output_dir)
    if(NOT vendor MATCHES "^(mbedtls|openssl|wg-go|wintun)$")
        message(FATAL_ERROR "No prebuilt archive configured for vendor '${vendor}'")
    endif()

    set(vendor_dir "${PP_VENDOR_ROOT}/${vendor}")
    if(NOT IS_DIRECTORY "${vendor_dir}")
        message(FATAL_ERROR "Prebuilt vendors root does not contain '${vendor}' in ${PP_VENDOR_ROOT}")
    endif()

    set(${output_dir} "${vendor_dir}" PARENT_SCOPE)
    message(STATUS "Using prebuilt ${vendor}")
endfunction()
