set(PARTOUT_ZIG_ARCH "${ARCH_NAME}")
if(PARTOUT_ZIG_ARCH MATCHES "^(arm64|aarch64)$")
    set(PARTOUT_ZIG_ARCH aarch64)
elseif(PARTOUT_ZIG_ARCH MATCHES "^(x64|x86_64|amd64)$")
    set(PARTOUT_ZIG_ARCH x86_64)
endif()

if(ANDROID)
    string(REGEX REPLACE "^android-" "" PARTOUT_ANDROID_API "${ANDROID_PLATFORM}")
    set(PARTOUT_ZIG_TARGET "${PARTOUT_ZIG_ARCH}-linux-android.${PARTOUT_ANDROID_API}")
    set(PARTOUT_ZIG_LIBC "${CMAKE_CURRENT_BINARY_DIR}/android.libc")
    file(WRITE "${PARTOUT_ZIG_LIBC}"
"include_dir=${CMAKE_SYSROOT}/usr/include
sys_include_dir=${CMAKE_SYSROOT}/usr/include/${CMAKE_LIBRARY_ARCHITECTURE}
crt_dir=${CMAKE_SYSROOT}/usr/lib/${CMAKE_LIBRARY_ARCHITECTURE}/${PARTOUT_ANDROID_API}
msvc_lib_dir=
kernel32_lib_dir=
gcc_dir=
")
elseif(APPLE)
    if(CMAKE_SYSTEM_NAME STREQUAL "iOS")
        set(PARTOUT_APPLE_OS ios)
        set(apple_sdk iphoneos)
        set(apple_minimum 16.0)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "tvOS")
        set(PARTOUT_APPLE_OS tvos)
        set(apple_sdk appletvos)
        set(apple_minimum 17.0)
    else()
        set(PARTOUT_APPLE_OS macos)
        set(apple_sdk macosx)
        set(apple_minimum 13.0)
    endif()
    if(CMAKE_OSX_DEPLOYMENT_TARGET)
        set(apple_minimum "${CMAKE_OSX_DEPLOYMENT_TARGET}")
    endif()
    if(CMAKE_OSX_SYSROOT)
        set(apple_sdk "${CMAKE_OSX_SYSROOT}")
    endif()
    execute_process(COMMAND xcrun --sdk "${apple_sdk}" --show-sdk-path
        OUTPUT_VARIABLE PARTOUT_APPLE_SDK OUTPUT_STRIP_TRAILING_WHITESPACE
        COMMAND_ERROR_IS_FATAL ANY)
    set(apple_simulator "")
    if(PARTOUT_APPLE_SDK MATCHES "[Ss]imulator")
        set(apple_simulator "-simulator")
    endif()
    set(PARTOUT_ZIG_TARGET "${PARTOUT_ZIG_ARCH}-${PARTOUT_APPLE_OS}.${apple_minimum}${apple_simulator}")
    if(PARTOUT_ZIG_ARCH STREQUAL "aarch64")
        set(apple_arch arm64)
    else()
        set(apple_arch "${PARTOUT_ZIG_ARCH}")
    endif()
    set(PARTOUT_APPLE_TARGET "${apple_arch}-apple-${PARTOUT_APPLE_OS}${apple_minimum}${apple_simulator}")
elseif(WIN32)
    set(PARTOUT_ZIG_TARGET "${PARTOUT_ZIG_ARCH}-windows-msvc")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(PARTOUT_ZIG_TARGET "${PARTOUT_ZIG_ARCH}-linux-gnu")
endif()
