name: Cache JSON
on:
  push:
    branches:
      - master
      - feature/update-api
    paths:
      - "API/**"
      - "Sources/APIBundle/JSON/**"
  schedule:
    - cron: '0 3 * * MON'
  workflow_dispatch:

jobs:
  store_to_cache:
    name: Store to cache
    runs-on: ubuntu-latest
    timeout: 5
    environment: production
    defaults:
      run:
        working-directory: ./API
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: API/package-lock.json
      - run: npm ci
      - name: Run tests
        run: npm test
      - name: Generate JSON
        run: npm run cache "${{ vars.CACHE_IDS }}"
      - name: Push to cache
        uses: tagus/git-deploy@v0.5.0
        with:
          changes: "cache/src"
          repository: git@github.com:passepartoutvpn/api-cache.git
          ssh_key: ${{ secrets.CACHE_DEPLOY_KEY }}
          name: API
          email: providers@passepartoutvpn.app
          branch: master
