name: Core Binary Release

on:
  workflow_dispatch:

jobs:
  publish_release:
    name: Publish release
    runs-on: macos-15
    timeout-minutes: 30
    steps:
      - uses: passepartoutvpn/action-prepare-xcode-build@master
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
      - uses: passepartoutvpn/action-release-binary-package@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          script: "scripts/ci-generate.sh"
          framework: "PartoutCore.xcframework"
          manifest-file: "Package.swift"
          gpg-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          prerelease: true
