name: Core Binary Release

on:
  workflow_dispatch:

jobs:
  run_tests:
    name: Run tests
    runs-on: macos-15
    timeout-minutes: 15
    steps:
      - uses: passepartoutvpn/action-prepare-xcode-build@master
        with:
          access_token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true
      - name: Run tests
        run: |
          swift test
  publish_release:
    name: Publish release
    runs-on: macos-15
    needs: run_tests
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16"
      - uses: passepartoutvpn/action-release-binary-package@master
        with:
          script: "scripts/ci-generate.sh"
          framework: "PartoutCore.xcframework"
          manifest-file: "Package.swift"
          gpg-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          prerelease: true
