name: Unit Tests

on:
  pull_request:
    types: [ opened, synchronize ]
    paths-ignore:
      - "README.md"
      - "**/*.md"
      - "scripts/*.sh"
      - "scripts/*.ps1"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  run_tests:
    name: ${{ matrix.job_name }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - job_name: Run Swift tests
            runner: macos-26
            suite: swift
          - job_name: Run Zig tests
            runner: ubuntu-latest
            suite: zig
          - job_name: Run Kotlin tests
            runner: ubuntu-latest
            suite: kotlin
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: partout-io/action-prepare-xcode-build@master
        if: matrix.suite == 'swift'
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Swift tests
        if: matrix.suite == 'swift'
        run: ci/run-swift-tests.sh
      - uses: mlugg/setup-zig@v2
        if: matrix.suite == 'zig'
      - name: Run Zig tests
        if: matrix.suite == 'zig'
        run: ci/run-tests.sh
      - uses: actions/setup-java@v5
        if: matrix.suite == 'kotlin'
        with:
          distribution: temurin
          java-version: 21
      - name: Run Kotlin tests
        if: matrix.suite == 'kotlin'
        run: ci/run-kotlin-tests.sh
